### ISSUE TITLE
Clarify AGPL status.

### ISSUE THREAD

**Issue by Jookia** [freeciv/freeciv-web#11]
The project says it's under the AGPL but all I can find are Javascript files under the GPLv2 (or later) when it comes to licensing information - It'd be great if licensing information is clarified such as AGPL version in the source code itself and whether it's upgradable to a later version.

**Comment by andreasrosdal** [comment]
Freeciv-web is AGPL licenced. Freeciv is GPL licenced.

**Comment by Jookia** [comment]
Could you please clarify this in the source code?

**Comment by andreasrosdal** [comment]
Done.

**Comment by Jookia** [comment]
Thanks so much.
