### ISSUE TITLE
There is no "Unload" hotkey for ships containing units to be unloaded

### ISSUE THREAD

**Issue by cpetry** [freeciv/freeciv-web#117]
User interface
Origin: Issue from TODO txt file. (refs #91)

There is no "Unload" hotkey for ships containing units to be unloaded. You have to click on the ship, then select each unit one by one, and it the ship has finished it's moves, the map recenters to the capital and then I have to go back and find the ship and repeat the process.

**Comment by ghost** [comment]
I think this issue has been fixed now. In this commit: 

https://github.com/freeciv/freeciv-web/commit/6d145a93d702a24e1b1b6a8c5068dc84c6589adc
