### ISSUE TITLE
UI Improovement: Catch browser Back

### ISSUE THREAD

**Issue by digitaldonkey** [freeciv/freeciv-web#12]
Maybe it's because I'm using a multitouch pad as mouse device, but I frequently have lost my (unsaved) game by accidentally triggering browser back while scrolling. Could also apply for the Back-Key of the browser. 

But independently from input device it would be great to have a "realy wanna leave page?" before leaving the page.

**Comment by andreasrosdal** [comment]
I agree. Freeciv-web used to have this functionslity, I can put it back.

Which browser are you using?

**Comment by digitaldonkey** [comment]
mostly chrome

**Comment by andreasrosdal** [comment]
Fixed.

**Comment by digitaldonkey** [comment]
cool!. No more lost games :dancer:
