### ISSUE TITLE
Research Tab doesn't refresh bulb information

### ISSUE THREAD

**Issue by Lexxie9952** [freeciv/freeciv-web#125]
When you are in the research tab, and pick a new technology, it doesn't update or refresh the display for number of bulbs.  For example,  if you are 19/28 bulbs on one technology, and changed your mind to pick a tehcnology that needs 55 bulbs, it will still say 19/28. 

This is probably the #1 most annoying bug in the whole game right now, in my opinion.

This might be related to a bug where you can't choose NOT to have a future tech research goal, once one is set.  That can be a problem sometimes if you have a high number of bulbs but want to wait to decide what to research next, because you might be getting tech from someone else, or have to make a big decision based on what will happen later.  If it's not related, then there you go, I just reported two bugs. ;~)

**Comment by ghost** [comment]
This has been fixed. I will release the fix to production soon.
