### ISSUE TITLE
Problem starting a foursome PBEM

### ISSUE THREAD

**Issue by Corbeau-1** [freeciv/freeciv-web#127]
We are having issues with starting a 4-player PBEM game. I started it, invited 3 friends (all registered), played a turn, ended turn and nothing happened. The game didn't show up on the page where PBEM games are listed. So I did everything again. Same result. Today a friend (Rango) also tried it, again, nothing.

**Comment by ghost** [comment]
The PBEM process had crashed in production. It has been restarted now, so the problem should be fixed. I will make a change so that the PBEM-process is restarted automatically once every day to prevent this from happening again.

**Comment by Corbeau-1** [comment]
Many thanks!

______________________________________________________________
