### ISSUE TITLE
Can't add/remove to city work list with double-click

### ISSUE THREAD

**Issue by lonemadmax** [freeciv/freeciv-web#129]
Until recently it was possible to remove an item from the work list by double-clicking it, and to add it by double-clicking in the production list. Now it only works the first time, and the dialog has to be closed and reopened to use it again.

Making the dialog modal brings the functionality back, but that doesn't explain why it's happening and, more importantly, defeats the recent work on non-modal dialogs.

**Comment by Lexxie9952** [comment]
I think someone changed it, this might be because during lag you keep trying, then you get that thing in the list 14 times.  It's too bad though, I think it was a good feature.
