### ISSUE TITLE
Can't change hometown after moving unit

### ISSUE THREAD

**Issue by digitaldonkey** [freeciv/freeciv-web#13]
With freeciv web I need to wait one turn, before the Home-Button (Unit Action) shows up. 
This is not the behaviour I know from other civ clients.

**Comment by andreasrosdal** [comment]
There is a "change homecity of unit" choice on the right-click menu. Does this solve your need?

**Comment by andreasrosdal** [comment]
Hi! Do you still have this problem?

**Comment by andreasrosdal** [comment]
Closing, since no answer and a very long time has past.
