### ISSUE TITLE
Profile Tab

### ISSUE THREAD

**Issue by Lexxie9952** [freeciv/freeciv-web#130]
Andreas told me he really liked this idea, and to post this idea here.  It's especially great for longturn games, but I can see it being good for Multiplayer with strangers, too.

 Often, when you meet another nation, you have no idea about them at all.  In real history, this isn’t the case.  The rulers of nations have a very public message about what their nation is and what it represents, and hearsay from travelers and other reputation precedes them. 

 Imagine in freeciv if  ...   in the Nations tab, there is a Player Profile button!  Click it to find out the “world story” on this nation.  Alternate names for the button could be Nation, Leader. 
 
Clicking it would give a profile.  Even if it's the simplest thing of all, just a half page of text.  This means that Players could advertise their style of play.  What makes them aggressive, what pleases them, under what terms they trade tech, their policy about embassies and diplomats, explorers, peace and alliances, territorial claims, reason for playing (conquest, making friends, growing large civilisation, etc.), they could put a Discord link to contact them, etc.
 
Without profiles, I feel like right now it feels like a high security prison where nations in different cells can pass each other little notes. The tab would become a hub for advertising your nation’s policies, position, style of play, and how to behave and interface around you, give opportunity to send message via discord (if they post a discord link), etc.  I feel this feature would not only be super easy to implement, but open up a whole greater dimension to the multiplayer aspect of the intrigue and fun it is to play against other humans. Right now other humans are almost the same as AI players except run by a human. This humanizes things a lot more. 

There is no reason not to do it, since the first version could be ultra-super-simple to implement:

Player Tab
1. Simplest Version of all - allows you to put in a link to a page with offsite text. Cick the button and it shows offsite text.  We can then just put in the simplest website folder somewhere on the server that allows players to edit one page of text. 

2. Integrated Version - allows you to click Player Tab for yourself, and a page pops up that lets you edit half page of text.  Other people clicking the tab then see a player profile with the text.

 3. Deluxe Version - future features can be added
 		a. Player can put in an avatar pic (link)
                 b. Lots of other features could be added later.  That's right, this is an idea that can really keep growing into something great!

**Comment by ghost** [comment]
Thanks for the suggestion, I think this is a great idea.

We need to fully think through all aspects of this, though. Please discuss possible risks with this, and how this content should be moderated. Who will moderate it?

**Comment by ghost** [comment]
Unless the risks of this is discussed, and solutions to the risks are presented, then I will close this issue soon.

**Comment by ghost** [comment]
I'm closing this issue, because there are too many risks and not enough resources to moderate such functionality.

**Comment by Lexxie9952** [comment]
The only risk I see is a link to a malware site in the profile ?  This could be prevented by simply not having external links, and hosting the simple text format profile description on the same server the game is played.  

Moderation seems to be a very rare issue, but might involve someone puts really slanderous abusive text in their description. They could be warned and the profile deleted or replaced with a read-only file that just blocks them from putting more things in.  

If something like that happened once every 4 or 5 months, that is not really a large resource drain I don't think.  Limiting public free speech because someone MIGHT be abusive with it, doesn't make sense, otherwise we'd just disable all public and private chat too.  I think the profile is MUCH LESS LIKELY to be used for abusive communication, than the other means of communicating in the chat console or in discord channels.

**Comment by ghost** [comment]
> Moderation seems to be a very rare issue, but might involve someone puts really slanderous abusive text in their description. 

This is why this feature will probably never happen. Sorry.
