### ISSUE TITLE
disable civil war in PBEM

### ISSUE THREAD

**Issue by drdogbot7** [freeciv/freeciv-web#131]
Capturing an opponent's capital city can still cause a civil war, which adds an AI player and breaks a PBEM game.

Could probably just set civilwarsize to 1000

I couldn't figure out how to change this option, or I would have created a pull request.

**Comment by ghost** [comment]
This is the settings file for PBEM:
https://github.com/freeciv/freeciv-web/blob/develop/publite2/pubscript_pbem.serv

**Comment by drdogbot7** [comment]
Cool. Submitted pull request.

**Comment by ghost** [comment]
Fixed here:  https://github.com/freeciv/freeciv-web/pull/132
