### ISSUE TITLE
I press "G" to go to a tile - how do I cancel the order?

### ISSUE THREAD

**Issue by stefek99** [freeciv/freeciv-web#133]

**Comment by ghost** [comment]
The Esc key. 

Is there a need to improve this?

**Comment by jarthurgross** [comment]
Not sure if this is what @stefek99 meant, but if I give a unit a goto order it can't complete in the current turn, it queues up a move for subsequent turns (indicated by the "G" beside the unit's icon) that can't be canceled by pressing the Esc key. I can sort of hack a cancel by ordering it to fortify, but then I won't be reminded automatically that I need to give orders to that unit next turn, so it would be nice if Esc (or "J" for "no orders") took care of this.

**Comment by stefek99** [comment]
`I can sort of hack a cancel by ordering it to fortify`

😇

Well hacked!

**Comment by i1abnrk** [comment]
Explore has the same issue of no abort command. Wait command doesn't work as expected.

**Comment by Lexxie9952** [comment]
Previously it used to be you can cancel orders by doing a "hack" of **S**entry then a **J**-do nothing.  But now someone made a change and this doesn't work, and there is no good way to cancel orders

**Comment by mchenryc** [comment]
The answer to this (as of [2018-02-25](https://github.com/freeciv/freeciv-web/blob/develop/freeciv-web/src/main/webapp/javascript/control.js#L1080)) seems to be <kbd>ctrl</kbd>-<kbd>J</kbd>.

@lonemadmax ok to close?

**Comment by lonemadmax** [comment]
It's <kbd>caps</kbd>-<kbd>J</kbd> (and it appears in the context menu, if you are not into shortcuts), but yeah.
Good hunt.
