### ISSUE TITLE
Display warning if a player wants to finish turn before all units have moved.

### ISSUE THREAD

**Issue by stefek99** [freeciv/freeciv-web#135]

**Comment by ghost** [comment]
This might be a good idea. However, the warning shoudn't annoy players who are determined to end their turn even without all units moved.

Patches welcome.

**Comment by ghost** [comment]
This can be fixed by adding a message when all units have been moved: "All units have moved now. You can end your turn now"

**Comment by stefek99** [comment]
> "All units have moved now. You can end your turn now"

Respectfully disagree.

Adding warning when finishing turn before all units moved !== displaying message when all units moved.

Main reason - accidental clicks.

Adding a keyboard shortcut `move to next available unit` seems handy too, probably already implemented.

**Comment by lonemadmax** [comment]
> Adding a keyboard shortcut `move to next available unit` seems handy too, probably already implemented.

'W' puts the focused unit (if any) into the wait queue (hey, unit, I'll come back to you later, please wait for orders) and focuses the next waiting one.

**Comment by ghost** [comment]
I have added a little check icon which will be displayed on the turn done button when all units have moved.
I hope that this will improve this issue. Therefore I'm closing this bugreport now.
