### ISSUE TITLE
Starting a game with players that don't exist

### ISSUE THREAD

**Issue by dsingleton86** [freeciv/freeciv-web#138]
Myself and a friend were looking into creating a game and didn't realise that there were no AI-controlled characters on freeciv-web.  There's a currently running game with the users `Mrpipes`, `Dsing`, `Bellend`, and `Bellcheese` where (apologies for the crude names, we thought they were going to be AI characters in a private game) `Bellend` and `Bellcheese` don't actually exist as users.

I'm wondering if it should be made so that games cannot be created with usernames that aren't registered in the system or something else could be done to prevent this happening in the future.
There's a game sat there now where we have both taken our turns and we are just going to have to wait until it expires...

thanks

_edit: this is for the play-by-email game_

**Comment by ghost** [comment]
Thanks for reporting this bug. I have added some more text to explain that the usernames must be of valid human players in the pbem creation dialog. 

I have added a TODO-item here to implement proper validation of all usernames when there are 3 or 4 players here:
https://github.com/freeciv/freeciv-web/blob/develop/freeciv-web/src/main/webapp/javascript/pbem.js#L257
