### ISSUE TITLE
Can't scroll in Research tab

### ISSUE THREAD

**Issue by jarthurgross** [freeciv/freeciv-web#139]
For over a week, I haven't been able to scroll left or right in the Research tab. I used to be able to accomplish this by right clicking some background point, and the technology tree would scroll left or right to center that background point I had clicked (much like panning works on the map), but now I get the standard right-click context menu.

Apparently this problem isn't universal, as a quick query on discord revealed that others have a scroll bar visible (I don't) and can also use the trackpad to scroll (I can't).

My browser is Firefox 57.0

**Comment by ghost** [comment]
This has been fixed now. Please report if you still get this problem.
