### ISSUE TITLE
Cannot trade tech

### ISSUE THREAD

**Issue by fuzzydunlop1** [freeciv/freeciv-web#140]
In long turn game 12, another player and i cannot trade tech. We can add other items to the agreement window but the two techs we want to trade, we can click them but nothing goes into the window. 

We have tried different browsers

**Comment by ghost** [comment]
Tech trading is disabled in Freeciv game 12. See here:
https://github.com/freeciv/freeciv-web/blob/develop/publite2/pubscript_longturn_6006.serv#L35
