### ISSUE TITLE
Chat recipient feature for chat window is great but is very hard to scroll through so many non-human nations.

### ISSUE THREAD

**Issue by Lexxie9952** [freeciv/freeciv-web#148]
![screen shot 2018-01-14 at 4 11 34 am](https://user-images.githubusercontent.com/32187224/34915819-49527724-f8e1-11e7-9dc9-786d6b04be91.png)

**Comment by ghost** [comment]
This has been fixed here:  https://github.com/freeciv/freeciv-web/commit/74daecf7d40753a6f449d15dcf0c97537fc3932d
