### ISSUE TITLE
Production Queue not really useful because requirements blocking

### ISSUE THREAD

**Issue by Lexxie9952** [freeciv/freeciv-web#149]
In production queue for cities, you want to do things like make a bank after a market, or a university after a library, a sewer after an aqueduct.

The way the interface is now:  it correctly doesn't give you the option to build something you don't have requirements for....

But, the amount of work involved to constantly put placeholder things into the production queue and constantly manage this queue becomes a huge pain that **_eliminates and breaks the whole benefit of why we have a queue_**

If you put aqueduct in queue twice, then after it made the first aqueduct, it would be nice if it automatically upgraded the aqueduct order to a sewer in this list.  Market becomes bank, library becomes uni, etc.  Then the queue would be useful and a huge time saver.  And we need time savers in the interface so that our game experience is more fun instead of constant management of so many little details.

**Comment by Lexxie9952** [comment]
People are talking about complex ways to solve it, but it seems a simple fix is just that you queue two libraries, then when it gets to the second library, instead of eliminating it from the list because you already have it, it just changes the order to a university automatically.  Same would be for temple > cathedral, market > bank > stock exchange, aqueduct > sewer, and maybe some others I didn't think of yet.

Caedo has mentioned that the normal freeciv client just has a way to toggle so that all things are in the option list, allowing for putting things in the queue which aren't yet allowed by current requirement buildings.

**Comment by lonemadmax** [comment]
The second option, having a checkbox to be able to add currently unreachable targets, like in the desktop client, might be the way to go. You examples may be clear cases in this ruleset, but what about Factory? Sometimes I want Factory -> Manufacturing plant, and sometimes I want Factory -> one of the energy plants (even a different one depending on the city).

It is also completely user driven and avoids surprises. Say I want a set of cities to have some improvements, a Library being one of them, but I don't want to add University. I hope someday we have named worklists, but even without them, I may just select those cities and blindly add the improvements to their list. An automatic upgrade to University in cities that already had Library is unwelcome.

And, though I have not looked at the code for some time, I'd say the elimination is done in the server and the first proposal cannot be implemented in the client.

**Comment by Lexxie9952** [comment]
OK lonemadmax, you really made a very clear case!  Thanks!  And you are right.  Also, it's probably much easier to code a checkbox.  I imagine this more like 10-15 minutes.  Hopefully someone can do this.  It would be a huge improvement!

**Comment by ghost** [comment]
Awesome @lonemadmax ! Released to production now.
