### ISSUE TITLE
Display Income on Tax-Rate Changing dialogue

### ISSUE THREAD

**Issue by digitaldonkey** [freeciv/freeciv-web#15]
It's a little difficult to change the tax rate without seeing the Effect on the Income before applying and looking at the home screen. Alternatively position the Info Bar with the Income more on top or turn the Tax-Rate-Change dialog a dialogue window.

**Comment by andreasrosdal** [comment]
This has been fixed in the latest version which was deployed to production today.
Can you please test it, and report back if it works correctly for you?

Also, please continue reporting any bugs you might find in Freeciv-web. Thanks a lot!
