### ISSUE TITLE
Counting citizens on city page becomes very tedious when you have >15 cities.

### ISSUE THREAD

**Issue by Lexxie9952** [freeciv/freeciv-web#153]
City management starts to take far too much time and scrutiny and careful counting of citizen icons.  When you get a lot of cities, you can end up spending 30 minutes or longer just counting little icons all the time, because you are making sure your cities' citizens are all the proper number of happy.

Imagine, for example, that the picture below is one of 35 cities you have:

![screen shot 2018-01-14 at 3 08 25 pm](https://user-images.githubusercontent.com/32187224/34921958-02a00e2e-f93e-11e7-9018-da3902eb94dc.png)

Your goal is to make sure every city is going to stay rapturing for a few turns.  35 times you have to count little green citizens and check for a food surplus in every city, clicking in and out from City List to City Detail. Make some adjustments in that city, then count citizens AGAIN to see if the adjustment was a success.

Imagine 30 seconds x 35 cities and it is just too much, even for a longturn game. But it's a dirty fact that for games with shorter turns, it becomes nearly impossible to manage your empire in the web client.

Now imagine that to the right of these citizens, it has another display that does the counting for you and right next to it is food surplus. The eye can take in the info and in only one second see if this city needs adjustment for happiness and food surplus.

**Comment by Lexxie9952** [comment]
a rough job just to show the idea, but you can see how much faster this would be to manage....

![moddedcity](https://user-images.githubusercontent.com/32187224/54759317-0cef2200-4bab-11e9-97b5-2b245c01c7f7.png)

Also displayed, since it's easy to do and avoids the need to leave this screen constantly to check, is to put the city status for Celebrating/Peace/Disorder to the far right.

**Comment by Lexxie9952** [comment]
I had another idea if this seems too difficult to do.  Even hovering over the icon of the green happy citizen, if the floating text said "7 happy citizens" instead of "one happy citizen", then right away you already know if you have 50% happy or not.  This might be a lot easier but still make it SOOO much easier for nations with >15 cities who are in the middle of a rapture growth.

**Comment by Lexxie9952** [comment]
![wheat](https://user-images.githubusercontent.com/32187224/54759241-ea5d0900-4baa-11e9-835d-f9878fe3ec33.png)

![city](https://user-images.githubusercontent.com/32187224/54759317-0cef2200-4bab-11e9-97b5-2b245c01c7f7.png)

Above:
**1.** Graphic asset for a wheat/food surplus icon. It is oversized.
**2.** Most recent mock-up which would also include city status of peace/celebrating/disorder without having to leave this screen every time to check.
**3.** Unhappy and Angry are not shown here because there are none. I believe showing stats for zero is messy clutter -- it is maybe better to conditionally leave blank the icon and stats when they are zero.  The space would be reserved and designated, so that everything has a space to fit and will either show or not show if it is relevant, but always in the same designated spot on the screen.

the graphic mock is just to show the quick concept: the order from left to right should, however, be: happy,content,unhappy,angry

**Comment by Lexxie9952** [comment]
![city screen](https://user-images.githubusercontent.com/32187224/54764055-48421e80-4bb4-11e9-9928-e2d3e40214c9.png)

**Comment by Lexxie9952** [comment]
Since the feature idea is to ELIMINATE the need to constantly flip screens, above is the second part of this feature request: availability of this info in the city list also.

In the above graphic, the numbers would probably be divided with the / character.  it is suggested that the third number be a sum of unhappy+angry because it is much easier to read and takes up less space. So this graphic would have an unhappy citizen icon, a + symbol, then an angry citizen icon, and the third number would be the sum of those 2. 

Alternatively it would not sum unhappy + angry and the numbers bellow would be h/c/u/a instead of h/c/u+a.  This would be technically cleaner and more accurate but not as good for "ergonomic perception" and rapid-Gestalt-uptake in 99.9% of the cases.

**Comment by Lexxie9952** [comment]
By having this info in both places, 
1. The city list screen is finally "compliant" with the same info shown in native client.
2. The need to always flip and switch between both screens constantly, or count icons, is finally solved.

One of the most time-consuming killers of game-fun and empire management goes from tedious, into a quick and fun process of spotting cities that need adjustment then diving in to fix them.

**Comment by andreasrosdal** [comment]
Can we close this now?

**Comment by andreasrosdalw** [comment]
Thanks to @RhueOfL for fixing this.
