### ISSUE TITLE
Should be able to target specific improvements with "Pillage"

### ISSUE THREAD

**Issue by jarthurgross** [freeciv/freeciv-web#155]
Currently, if I instruct a unit to pillage a tile with multiple improvements&mdash;*e.g.*, irrigation and road&mdash;Freeciv web automatically selects what to pillage based on some predefined ordering, in this case selecting irrigation for pillaging. The standalone Freeciv client, on the other hand, allows for selection of a specific improvement. Within Freeciv web such behavior can be achieved by instructing multiple units to pillage on the same tile (they will pillage different improvements in parallel) and then assigning new tasks to all but the unit pillaging the desired (or rather, undesired) improvement. Not only is this workaround inconvenient, but it is predicated on the availability of other nearby units in an arbitrary way.

It would enhance gameplay if Freeciv web presented a selection menu when ordering a unit to pillage a tile with multiple improvements.

**Comment by lonemadmax** [comment]
Closed with e39f3173a3f7adba0794fd5848605a9468e815fe
