### ISSUE TITLE
Game is "stuck"

### ISSUE THREAD

**Issue by arran4** [freeciv/freeciv-web#158]
So in short. We are at a situation where https://play.freeciv.org/game/list?v=play-by-email claims that we are on turn 103, and that it's my turn. However, we have both already had our 103 turn. We have both received an email for that turn.

When we go back to view that email and click the link, it says that we have already had our turn, and unable to continue.

**Comment by ghost** [comment]
Can you please clear your browser cache, and try clicking on your latest link again?

**Comment by arran4** [comment]
Seems to have worked.
