### ISSUE TITLE
Buying Buildings

### ISSUE THREAD

**Issue by Vivek99** [freeciv/freeciv-web#16]
Hey guys, why can't we buy buildings, with our gold anymore? Gold is basically useless!

**Comment by andreasrosdal** [comment]
Hello, I just tested, and I was able to buy buildings on the current production version of Freeciv-web.

Please provide some more information. Do you get some error-message when trying to buy buildings? Are you able to buy units? What kind of device are you using to play Freeciv-web, is it a desktop or mobile device?

**Comment by Vivek99** [comment]
[image: Inline image 1]


There is no buy option, I play on Google Chrome.

**Comment by Vivek99** [comment]
![image](https://cloud.githubusercontent.com/assets/14132833/9699826/7f0e4a44-53bd-11e5-96fe-ada76f576309.png)

**Comment by andreasrosdal** [comment]
Try playing the game in fullscreen-mode,  and you should see the buy-botton.

I will create a fix which solves this in the next version.

**Comment by Vivek99** [comment]
Thank you very much :)
