### ISSUE TITLE
Default SSL configuration missing

### ISSUE THREAD

**Issue by ghost** [freeciv/freeciv-web#169]
The default SSL configuration in the Vagrant image is not working.
It is configured here:
https://github.com/freeciv/freeciv-web/blob/develop/nginx/sites-available/freeciv-web#L5

I suggest to remove this one line, and just support HTTP by default on Vagrant.
That means it will be easier to get a working system up and running.

If someone wants HTTPS with Freeciv-web then they can run a Let's Encrypt client.

**Comment by lonemadmax** [comment]
Works for me. My browser (firefox) warns that it is an insecure self signed certificate and I have to add an exception, but that is expected.

Is it maybe the VM installed before changing the vagrant file to use the test mode? In that case, you are right. You have to either comment out that line or add a certificate. A self-signed one for localhost can be generated and put where the default config expects it by running the following commands: https://github.com/freeciv/freeciv-web/blob/3b53280e17e73e796cf8a8530f245242606ae0d1/scripts/install/install.sh#L295-L299

**Comment by lonemadmax** [comment]
I'm closing this as not-a-bug. Don't hesitate to reopen if it's a post 08e3fa393915890553524f84c927bdc995ad68dc installation and you have more info about the problem.
