### ISSUE TITLE
web client downloaded save game in "1907" shows "1902"  and earlier game state when restored

### ISSUE THREAD

**Issue by DrPaulBrewer** [freeciv/freeciv-web#17]
I'm posting a save game that shows an earlier year and game state when restored. 

I am posting it in the hope that it can be useful in debugging the save/restore process for everyone and don't expect a personal reply.

A single player web client game was played as "Frank" on a Toshiba Chromebook 2.  For unknown reasons, the localStorage savegames are not reliable on this device so to save I will download the file and not trust it to localStorage.

save file Frank 1907 shows 1902 year and 1902 game state on restoration -- 

https://drive.google.com/file/d/0B-XXSCz5WC7NUnJNV3NFNDMxZ3M/view?usp=sharing 

Earlier "1902" save file --

https://drive.google.com/file/d/0B-XXSCz5WC7NaXBXODhrdjhQamM/view?usp=sharing

**Comment by andreasrosdal** [comment]
Thanks for reporting this bug. Do you have a reliable way to reproduce this problem with savegames?
Do you think the problem is specific to Chromebooks, or do you get the same problem with Chrome on a regular computer? I would be interested in more details about this problem.

**Comment by andreasrosdal** [comment]
Freeciv-web now has a new savegame system, where savegames are stored on the server. Therefor this bugreport is not relevant any more. Please report your feedback on the new savegame system.
