### ISSUE TITLE
Trackjs token should be removed from source

### ISSUE THREAD

**Issue by mchenryc** [freeciv/freeciv-web#175]
The trackjs token is currently in the committed code. Unless this is publicly available, the token should be part of the server's environment variables, read by the servlet, and injected as a global JS constant. The trackjs `<script...` tags should be protected by testing, and use this variable, not by comparing the current servername to `fcwHost`.

OTOH, if user-metrics are publicly available, cool - but we should include information on how to access them.

If not public, I would also recommend generating a new token (and permanently disabling the old through whatever means trackjs provides), rather than [rewriting](https://help.github.com/articles/removing-sensitive-data-from-a-repository/) [history](https://medium.com/bam-tech/remove-sensitive-information-from-your-git-repository-10cb421f1b84), to erase it from git.

**Comment by andreasrosdalw** [comment]
The token can be public.

**Comment by lonemadmax** [comment]
That, the ads token, the captcha token, the mail server for pbem and other messages... They are in the backlog of changes related to configuration.

The tokens are public, as they've been in the repo for quite some time. The access to the data is not, and I don't think it should be. They come from the days when this was the repository for play.freeciv.org.

There are still hits, and they don't come only from my tests, so other users either have not noticed or don't care. But yes, they will all be another configuration option like the rest some day.

**Comment by lonemadmax** [comment]
BTW, not knowing good practice, is there a reason to separate some servlet config data into [config.properties](https://github.com/freeciv/freeciv-web/blob/develop/freeciv-web/src/main/webapp/WEB-INF/config.properties.dist) and not put it in [web.xml](https://github.com/freeciv/freeciv-web/blob/develop/freeciv-web/src/main/webapp/WEB-INF/web.xml)? The first commit indicates having it in an untracked file (having config.properties.dist in the repo but using config.properties), but that can also be done with web.xml.dist -> web.xml.

**Comment by mchenryc** [comment]
The odd thing to me is testing for hostname. That's bound to change, and odd, since it's not _host_ specific, but simply whether or not you want it to load - and have a key. With N virtual hosts behind a load-balancer, they won't have the same hostname. Or there could be N different public instances, all of which want to use their own tracking key. Lots of plausible scenarios can be made up, the point being that if you want to load tracking, you have to have a tracking key - so have a config setting for that key (commented out in the default) and load the tracking software, based on whether that key has been set. Now your host name is irrelevant.

Any Server specific settings shouldn't be in web.xml - it should just configure your software components based on the configurations. Configuration could come from env. specific config file, or loaded through some environmental means (e.g. secrets not for source control). If you move the war file to another server, whether it is just a different environment (dev, qa, uat, prod), a different company it just reads config to determine how to connect things and few informational bits. e.g. web.xml should use the database server specified in the config to configure the drivers. One config is specified for the dev, another for production... another for my local dev env, etc. Config could come from files, or overridden with environment variables. The point: configurable things should come from outside the compiled bundle.

**Comment by mchenryc** [comment]
@lonemadmax: https://12factor.net/

I was looking for that, but couldn't come up with the term "12 factor."  "12 best practices," "12 good things to do," "12 actions of awesomeness"... nothing was working for me last night...

As for properties, configuration is usually separated into a default file (e.g. `application.properties`) and environment specific overrides (e.g. `application-dev.properties`, `application-prod.properties`, etc...). Spring has [comprehensive libraries](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config-profile-specific-properties) for this, as does Apache commons. "profiles" in Spring go further, are not mutually exclusive, and can be combined, so you could "turn on" or various configurations by setting the `spring.profiles.active` environment variable. e.g. `dev,inmem`, vs `prod,mysql` to specifying configuration sets by restarting your server / different environment settings. Secrets are often injected directly via environment variable, or in more complex environments, with a token (like an ssh key) used to authenticate and retrieve configuration securely through a configuration specific server as needed.
