### ISSUE TITLE
Disable webgl_vision_cheat_temporary.patch for LongTurn and pbem

### ISSUE THREAD

**Issue by andreasrosdalw** [freeciv/freeciv-web#196]
This is a general improvement-issue for Freeciv WebGL 3D, where we can discuss and propose any specific improvements to Freeciv WebGL 3D.

It can currently be tested here: https://www.isotrident.com/webclient/?action=new&renderer=webgl

Source: https://github.com/freeciv/freeciv-web/tree/develop/freeciv-web/src/main/webapp/javascript/webgl

**Comment by lonemadmax** [comment]
First of all, I'm not a 3D user (I'm not into 3D and my hardware is not powerful enough), so you may discard my comments.

One thing that bothers me is the aptly named [webgl_vision_cheat_temporary.patch](https://github.com/freeciv/freeciv-web/blob/develop/freeciv/patches/webgl_vision_cheat_temporary.patch). I guess doing without that info may need a big rewrite in the handling of new tiles and possibly in drawing the known ones, if it can be done at all. How about disabling 3D for longturn and maybe pbem (if the server knows when a game is of that type), and not sending that data to clients in those cases? The singleplayer type with multiple human players would still be an issue.

Another point is support for wrapping maps. Not an issue when you start a 3D game, only when you switch to 3D graphics from a 2D one.

**Comment by andreasrosdalw** [comment]
> One thing that bothers me is the aptly named webgl_vision_cheat_temporary.patch. How about disabling 3D for longturn and maybe pbem

Yes, this is a good idea.

**Comment by andreasrosdalw** [comment]
Fixed here: https://github.com/freeciv/freeciv-web/commit/29283d90b702c15e2fab46c76bbf1c8be6bae8a4
