### ISSUE TITLE
Map for minified code not generated on rebuild

### ISSUE THREAD

**Issue by lonemadmax** [freeciv/freeciv-web#205]
As indicated in https://github.com/samaxes/minify-maven-plugin/issues/142, the source map is not generated and "linked" if it already exists when rebuilding the code. There's an easy workaround now in [build-js.sh](https://github.com/freeciv/freeciv-web/blob/develop/freeciv-web/build-js.sh#L6-L8), but not in [build.sh](https://github.com/freeciv/freeciv-web/blob/develop/freeciv-web/build.sh). I wonder if it'd be better to include the deletion somewhere in the pom instead of those scripts, or even add the clean phase to flyway:migrate and package.

**Comment by mchenryc** [comment]
Adding the source-map-deletion-workaround to the pom is a good idea. If added to the `initialize` [phase](https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html), it would happen for any build script, at the appropriate time.

Note that Flyway a tool to migrate/update the DB - only one part of proj. initialization. In Freeciv-web, the pom declares it's use, but does not declare an execution for it - thus by default it does not run during the normal maven lifecycle. In `build.sh` maven is told to execute that plugin explicitly prior to `package`. It is independent of Javascript issues, and could (should?) be removed from maven, and the flyway library used during application runtime startup to ensure the db is up-to-date. I expect that is more typical (all uses I've seen of flyway did this) as maven is generally not run on production servers.
