### ISSUE TITLE
Remove play.freeciv.org specific items.

### ISSUE THREAD

**Issue by lonemadmax** [freeciv/freeciv-web#209]
The "webpages" part of this repo includes what was used in play.freeciv.org. With the site demise, its function is now to serve as an entry point for developers/testers and a sample or template for the brave admins that may want to host a server. There are still quite a few items left, from names or images to API tokens.

- [X] TrackJs. Set as a [config option](https://github.com/freeciv/freeciv-web/commit/185722bcdb1dea8bf465bfa88f5e2b4151af1bdd#diff-afc84ddeef90e9ba05426da7ce18f0f1R6) in 185722bcdb1dea8bf465bfa88f5e2b4151af1bdd.
- [X] Google Analytics. Set as a [config option](https://github.com/freeciv/freeciv-web/commit/fb20a17500b4d2c4cc7929284ddf97a5642c9b3f#diff-afc84ddeef90e9ba05426da7ce18f0f1R6) in fb20a17500b4d2c4cc7929284ddf97a5642c9b3f.
- [x] Google reCAPTCHA. There is a [config option](https://github.com/freeciv/freeciv-web/blob/23968d0f193097ac8a19d6a608d841e9e0c2f1cb/freeciv-web/src/main/webapp/WEB-INF/config.properties.dist#L1), but it doesn't work as the previous ones. The external script is [always loaded](https://github.com/freeciv/freeciv-web/blob/23968d0f193097ac8a19d6a608d841e9e0c2f1cb/freeciv-web/src/main/webapp/webclient/index.jsp#L65), and disabled when there is a special value (the provided "secret goes here") instead of empty or undefined. There's also a hardcoded key in [pregame.js](https://github.com/freeciv/freeciv-web/blob/23968d0f193097ac8a19d6a608d841e9e0c2f1cb/freeciv-web/src/main/webapp/javascript/pregame.js#L30). Other files to touch if this is changed: [NewPBEMUser.java](https://github.com/freeciv/freeciv-web/blob/develop/freeciv-web/src/main/java/org/freeciv/servlet/NewPBEMUser.java) and [ResetPassword.java](https://github.com/freeciv/freeciv-web/blob/develop/freeciv-web/src/main/java/org/freeciv/servlet/ResetPassword.java). ba41c11875a4af9f8942a8ddd355e43efbf4358b and 16fbba738ac29f5147cf90e09f8d03f82ffa8869.
- [X] Google [site verification key](https://github.com/freeciv/freeciv-web/blob/23968d0f193097ac8a19d6a608d841e9e0c2f1cb/freeciv-web/src/main/webapp/WEB-INF/jsp/fragments/head.jsp#L21). Removed in b874de50ae7a25001f176a3418f59d1ef20d0fe5.
- [X] Addthis widgets: [details.jsp](https://github.com/freeciv/freeciv-web/blob/23968d0f193097ac8a19d6a608d841e9e0c2f1cb/freeciv-web/src/main/webapp/WEB-INF/jsp/game/details.jsp#L8), [list.jsp](https://github.com/freeciv/freeciv-web/blob/23968d0f193097ac8a19d6a608d841e9e0c2f1cb/freeciv-web/src/main/webapp/WEB-INF/jsp/game/list.jsp#L9) and [freeciv-earth](https://github.com/freeciv/freeciv-web/blob/23968d0f193097ac8a19d6a608d841e9e0c2f1cb/freeciv-web/src/main/webapp/freeciv-earth/index.jsp#L40). Removed in b874de50ae7a25001f176a3418f59d1ef20d0fe5.
- [X] Google ads. Quite a few places in [freeciv-earth](https://github.com/freeciv/freeciv-web/blob/develop/freeciv-web/src/main/webapp/freeciv-earth/index.jsp), [index.jsp](https://github.com/freeciv/freeciv-web/blob/develop/freeciv-web/src/main/webapp/WEB-INF/jsp/index.jsp), [hall_of_fame.jsp](https://github.com/freeciv/freeciv-web/blob/develop/freeciv-web/src/main/webapp/WEB-INF/jsp/game/hall_of_fame.jsp) and [list.jsp](https://github.com/freeciv/freeciv-web/blob/develop/freeciv-web/src/main/webapp/WEB-INF/jsp/game/hall_of_fame.jsp). Removed in b874de50ae7a25001f176a3418f59d1ef20d0fe5.
- [X] Discord: [frame in main page](https://github.com/freeciv/freeciv-web/blob/23968d0f193097ac8a19d6a608d841e9e0c2f1cb/freeciv-web/src/main/webapp/WEB-INF/jsp/index.jsp#L449) and [link in menu](https://github.com/freeciv/freeciv-web/blob/23968d0f193097ac8a19d6a608d841e9e0c2f1cb/freeciv-web/src/main/webapp/WEB-INF/jsp/fragments/header.jsp#L40). Removed in b874de50ae7a25001f176a3418f59d1ef20d0fe5.
- [x] Mapbox: [earth.js](https://github.com/freeciv/freeciv-web/blob/23968d0f193097ac8a19d6a608d841e9e0c2f1cb/freeciv-web/src/main/webapp/freeciv-earth/earth.js#L26). fcd1782ee03bb5f1acd9f7d810d3dc6d1d25d0da
- [X] Blog: [link](https://github.com/freeciv/freeciv-web/blob/23968d0f193097ac8a19d6a608d841e9e0c2f1cb/freeciv-web/src/main/webapp/WEB-INF/jsp/fragments/header.jsp#L47), [feed](https://github.com/freeciv/freeciv-web/blob/23968d0f193097ac8a19d6a608d841e9e0c2f1cb/freeciv-web/src/main/webapp/WEB-INF/jsp/index.jsp#L436), [styles](https://github.com/freeciv/freeciv-web/blob/23968d0f193097ac8a19d6a608d841e9e0c2f1cb/freeciv-web/src/main/webapp/WEB-INF/jsp/index.jsp#L23) and [loader](https://github.com/freeciv/freeciv-web/blob/23968d0f193097ac8a19d6a608d841e9e0c2f1cb/freeciv-web/src/main/webapp/static/javascript/index.js#L16). Removed in b874de50ae7a25001f176a3418f59d1ef20d0fe5.

These may be removed, left as they are (as a kind of sample site) or left with the keys/ids in the config file.

It'd be nice to know what the people who have built a server (or even thought of doing it) think.

**Comment by andreasrosdalw** [comment]
Google site vk, addthis, ads, discord and blog can at least be removed. Isotrident was also shutdown.
