### ISSUE TITLE
New PBEM user not working on mobile

### ISSUE THREAD

**Issue by andreasrosdalw** [freeciv/freeciv-web#229]
The new PBEM user account doesn't work on mobile devices, because the dialog becomes too high, and the Submit button falls outside of the visible screen area.

**Comment by lonemadmax** [comment]
Could you test 6a2644eb2dbf38938958e8ae1d63ea346b3c00d7 with the real device? I've gone down to 320x480 in devtools and though crammed and difficult, it at least doesn't leave you out now. You have it live at [movingborders](https://fcw.movingborders.es/) if you don't have a build handy.

It has the drawback of sometimes having to scroll for menu items in the diplomacy dialog even in a big window.

**Comment by andreasrosdalw** [comment]
I can't test anything. Just test it in production.

**Comment by lonemadmax** [comment]
That's what the "You have it live at [link]" was for ;-)

**Comment by andreasrosdalw** [comment]
I can confirm that this is fixed.
