### ISSUE TITLE
Effect of Statue of Liberty missing

### ISSUE THREAD

**Issue by digitaldonkey** [freeciv/freeciv-web#23]
After having built the statue of liberty I couldn't switch to a governmental form I didn't discover yet. 
This would be freeciv default behavior and is also mentioned in the statue's explanation text.

**Comment by andreasrosdal** [comment]
Yes, this is a bug. Patches welcome. 

The change should be pretty easy, I can help anyone get the change done.

**Comment by andreasrosdal** [comment]
This has now been fixed.
