### ISSUE TITLE
Some freeciv-web hosting suggestions

### ISSUE THREAD

**Issue by andreasrosdalw** [freeciv/freeciv-web#235]
@lonemadmax I suggest this for https://fcw.movingborders.es/ :
-Remove the "Please note:" on the frontpage.
-Get a better domain name than the movingborders.es.
-Look for an even cheaper server at hetzner or elsewhere.
-I can help with more donations if you need.

**Comment by lonemadmax** [comment]
First of all, thank you for your donation and for all your work in freeciv-web.

The intro makes it look second-class, fragile, unprofessional... and it's on purpose. The site was born from frustration, having seen a little flow of people asking for singleplayer once freecivweb.org was running, and that day seeming to never come. But I still believe in having a single place, and that not being my site.

For the same reason I didn't want yet another direct reference to freeciv, civ or anything similar in the domain name that may mistake it with current or former sites. Moving borders is part of what you do in the game, so is adequate enough. Somewhat. More or less. If you squint just right.

Fuzzy has already set some redirects from singleplayer.freecivweb.org and pbem.freecivweb.org, though once you load them the URL is again fcw.movingborders.es. I'm also not in the SEO game. The site is for those who feel the need to have a server to play in, not to attract new people or be the center of gravity of a community.

Money is not an issue yet. I budgeted enough for a year, and fcw.movingborders.es should be unnecessary long before that.

When year end approaches I may reconsider all your points if we still don't have the one community server to rule them all.
