### ISSUE TITLE
Calling freeciv-web with a --file argument results in a segmentation fault

### ISSUE THREAD

**Issue by lonemadmax** [freeciv/freeciv-web#239]

**Comment by lonemadmax** [comment]
Tracing points to https://github.com/lonemadmax/freeciv-web/blob/ffcad844cd8c859b98b02f53209eff0b27cb3fc4/freeciv/patches/savegame.patch#L72
When `handle_stdin_input_real` > `load_command` is called from the console or due to command line arguments, `caller` is NULL.

**Comment by mchenryc** [comment]
@lonemadmax looking for a volunteer?
