### ISSUE TITLE
Diplomat: "Investigate City" causes UI Hang

### ISSUE THREAD

**Issue by digitaldonkey** [freeciv/freeciv-web#24]
In the current version my UI breaks in Firefox when i Try to investigate a enemy city. 

Reproduce: Try investigate the city Aldosa in attached save game. 
[freecivweb-digitaldonkey of the Raramuri in year_ 1500CE (T200).js.zip](https://github.com/freeciv/freeciv-web/files/120323/freecivweb-digitaldonkey.of.the.Raramuri.in.year_.1500CE.T200.js.zip)

**Comment by andreasrosdal** [comment]
Hi Digitaldonkey, and thanks for the bugreport.

This bug has been fixed and pushed to the production server. Please use  Ctrl + F5 to reload the game to clear cached JavaScript.

Can you please verify that the problem has been fixed?

Andreas

**Comment by digitaldonkey** [comment]
Working! Thanks.

**Comment by andreasrosdal** [comment]
Great! What is the next most important thing to improve?

**Comment by digitaldonkey** [comment]
haha. Rather little Things concerning Unit/City UI

Some userstories
I want to activate/move the most Veteran unif out of a city. If there are more than one, it's a hard to select the right one.

I want to activate a unit (from within a city) which is not at home (it's hard, you because there is only the Home, not the current city displayed.

I have a hip full of Workers. How I select the ones who are not yet transforming terrain. I would need the status (F/O/S/...) at the Unit window. 

I wanna load/unload units from boats.
