### ISSUE TITLE
Keyboard shortcuts not working

### ISSUE THREAD

**Issue by andreasrosdalw** [freeciv/freeciv-web#245]
The keyboard shortcuts are not working, for example pressing G for goto.

http://144.76.115.248

**Comment by lonemadmax** [comment]
From the separation of key handlers in https://github.com/freeciv/freeciv-web/pull/223.
After some dialogs are closed, the focus does not return to where it was, and the map keyhandler is not active. Clicking the map canvas (or map tab) makes it active again.
