### ISSUE TITLE
compilation an standalone game on arm

### ISSUE THREAD

**Issue by ghost** [freeciv/freeciv-web#250]
Hi, I cant use vagrant on raspberry pi (I am unable to install virtualbox on arm), there its any clean way to achieve an standalone game for raspberry pi? My raspbian its opengl conformant (mesa 19)

**Comment by lonemadmax** [comment]
Opengl won't help for the server.

This is what I can think of:
- Use other virtualization system, if you are so inclined. There's nothing in freeciv-web requiring virtualbox, it's just that there's already a Vagrantfile point to an image that works with it.
- [Try docker](https://github.com/freeciv/freeciv-web#running-freeciv-web-on-docker).
- Try a direct install. If raspbian has the same packages as debian, it may work. Add your system in the [script selector](https://github.com/freeciv/freeciv-web/blob/develop/scripts/install/systems) (you can find the vendor string with `lsb_release -is`, and the release with `lsb_release -cs`. Then run `scripts/install/install.sh`. That, if the same debian script works, will apt-get all needed packages, fetch the freeciv server code, compile it, and do everything else to get freeciv-web running directly in your system.

I'm not sure any of that will work. Or that installing freeciv-web on a raspberry pi is a good idea. Just starting freeciv-web in the VM I'm using right now goes from 270MB to 770MB of used RAM. A few minutes of playing a sample game adds some 100MB. I don't want to know how far it'd go with several games with a big map and a dozen players.

Now, if you try any of those methods, please tell us whether they worked. If the last one works, send a patch to include raspbian to `scripts/install/systems`, and please test from time to time that it still works.

**Comment by ghost** [comment]
Wow, thanks for the detailed reply. I will try my best

**Comment by ghost** [comment]
ive tried the last one because for me it was the clean way. dindt run.
pi@pi:~/Desktop/freeciv-web/scripts $ ./start-freeciv-web.sh 
./start-freeciv-web.sh: línea 9: aviso: setlocale: LC_ALL: no se puede cambiar el local (en_US.UTF-8): No existe el fichero o el directorio
Starting up Freeciv-web: nginx, tomcat, publite2, freeciv-proxy.
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
Starting nginx first.
Job for nginx.service failed because the control process exited with error code.
See "systemctl status nginx.service" and "journalctl -xe" for details.
Starting up Tomcat
Starting publite2
starting meta-stats.py
Will sleep for 8 seconds, then do a status test...
Starting Freeciv-Earth-mapgen.
Publite2 started
Starting Freeciv-PBEM
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
Checking that Freeciv-web is running correctly... (-v for verbose)

Checking nginx                                     Down
Checking Tomcat                                    OK!
Checking freeciv-web on Tomcat                     OK!
Checking Tomcat DB connection                      Down
Checking Pubstatus                                 OK!
Checking Mailstatus                                OK!
Checking freeciv-proxy directly                    OK!
Checking freeciv-proxy through nginx               Down
Checking WebSocket directly (freeciv-proxy)        OK!
Checking WebSocket through nginx                   Down
Checking freeciv-web (spawned by publite2)         OK!
Checking webclient.min.js generation               Down
Checking tileset generation                        Down

--------------------------------
Check of Freeciv-web is done!

[install.log](https://github.com/freeciv/freeciv-web/files/2947970/install.log)

**Comment by ghost** [comment]
pi@pi:~/Desktop/freeciv-web/scripts $ journalctl -xe
mar 09 00:44:30 pi systemd[1]: anacron.timer: Adding 2min 55.328263s random time.
mar 09 00:45:01 pi sudo[2423]:       pi : TTY=pts/0 ; PWD=/home/pi/Desktop/freeciv-web/scripts ; USE
mar 09 00:45:01 pi sudo[2423]: pam_unix(sudo:session): session opened for user root by (uid=0)
mar 09 00:45:01 pi sudo[2423]: pam_unix(sudo:session): session closed for user root
mar 09 00:45:02 pi sudo[2434]:       pi : TTY=pts/0 ; PWD=/home/pi/Desktop/freeciv-web/scripts ; USE
mar 09 00:45:02 pi sudo[2434]: pam_unix(sudo:session): session opened for user root by (uid=0)
mar 09 00:45:03 pi systemd[1]: Starting A high performance web server and a reverse proxy server...
-- Subject: Unit nginx.service has begun start-up
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- Unit nginx.service has begun starting up.
mar 09 00:45:03 pi nginx[2465]: nginx: [emerg] BIO_new_file("/etc/nginx/ssl/freeciv-web.crt") failed
mar 09 00:45:03 pi nginx[2465]: nginx: configuration file /etc/nginx/nginx.conf test failed
mar 09 00:45:03 pi systemd[1]: nginx.service: Control process exited, code=exited status=1
mar 09 00:45:03 pi systemd[1]: Failed to start A high performance web server and a reverse proxy ser
-- Subject: Unit nginx.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- Unit nginx.service has failed.
-- 
-- The result is failed.
mar 09 00:45:03 pi systemd[1]: nginx.service: Unit entered failed state.
mar 09 00:45:03 pi systemd[1]: nginx.service: Failed with result 'exit-code'.
mar 09 00:45:03 pi sudo[2434]: pam_unix(sudo:session): session closed for user root
mar 09 00:45:09 pi sudo[2897]:       pi : TTY=pts/0 ; PWD=/home/pi/Desktop/freeciv-web/scripts ; USE
mar 09 00:45:09 pi sudo[2897]: pam_unix(sudo:session): session opened for user root by (uid=0)
mar 09 00:45:10 pi sudo[2897]: pam_unix(sudo:session): session closed for user root
lines 2201-2229/2229 (END)
mar 09 00:44:30 pi systemd[1]: anacron.timer: Adding 2min 55.328263s random time.
mar 09 00:45:01 pi sudo[2423]:       pi : TTY=pts/0 ; PWD=/home/pi/Desktop/freeciv-web/scripts ; USER=root ; COMMAND=/bin/ln -f /etc/nginx/sites-a
mar 09 00:45:01 pi sudo[2423]: pam_unix(sudo:session): session opened for user root by (uid=0)
mar 09 00:45:01 pi sudo[2423]: pam_unix(sudo:session): session closed for user root
mar 09 00:45:02 pi sudo[2434]:       pi : TTY=pts/0 ; PWD=/home/pi/Desktop/freeciv-web/scripts ; USER=root ; COMMAND=/usr/sbin/service nginx start
mar 09 00:45:02 pi sudo[2434]: pam_unix(sudo:session): session opened for user root by (uid=0)
mar 09 00:45:03 pi systemd[1]: Starting A high performance web server and a reverse proxy server...
-- Subject: Unit nginx.service has begun start-up
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- Unit nginx.service has begun starting up.
mar 09 00:45:03 pi nginx[2465]: nginx: [emerg] BIO_new_file("/etc/nginx/ssl/freeciv-web.crt") failed (SSL: error:02001002:system library:fopen:No 
mar 09 00:45:03 pi nginx[2465]: nginx: configuration file /etc/nginx/nginx.conf test failed
mar 09 00:45:03 pi systemd[1]: nginx.service: Control process exited, code=exited status=1
mar 09 00:45:03 pi systemd[1]: Failed to start A high performance web server and a reverse proxy server.
-- Subject: Unit nginx.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- Unit nginx.service has failed.
-- 
-- The result is failed.
mar 09 00:45:03 pi systemd[1]: nginx.service: Unit entered failed state.
mar 09 00:45:03 pi systemd[1]: nginx.service: Failed with result 'exit-code'.
mar 09 00:45:03 pi sudo[2434]: pam_unix(sudo:session): session closed for user root
mar 09 00:45:09 pi sudo[2897]:       pi : TTY=pts/0 ; PWD=/home/pi/Desktop/freeciv-web/scripts ; USER=root ; COMMAND=/usr/sbin/service tomcat8 sta
mar 09 00:45:09 pi sudo[2897]: pam_unix(sudo:session): session opened for user root by (uid=0)
mar 09 00:45:10 pi sudo[2897]: pam_unix(sudo:session): session closed for user root
~
~
~
~
~
~
~
~
~
~
~
~

pi@pi:~ $ systemctl status nginx.service
● nginx.service - A high performance web server and a reverse proxy server
   Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2019-03-09 00:45:03 -03; 4min 47s ago
     Docs: man:nginx(8)
  Process: 2465 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, st

mar 09 00:45:03 pi systemd[1]: Starting A high performance web server and a reverse proxy server...
mar 09 00:45:03 pi nginx[2465]: nginx: [emerg] BIO_new_file("/etc/nginx/ssl/freeciv-web.crt") failed
mar 09 00:45:03 pi nginx[2465]: nginx: configuration file /etc/nginx/nginx.conf test failed
mar 09 00:45:03 pi systemd[1]: nginx.service: Control process exited, code=exited status=1
mar 09 00:45:03 pi systemd[1]: Failed to start A high performance web server and a reverse proxy ser
mar 09 00:45:03 pi systemd[1]: nginx.service: Unit entered failed state.
mar 09 00:45:03 pi systemd[1]: nginx.service: Failed with result 'exit-code'.
lines 1-13/13 (END)

**Comment by Askmewho** [comment]
I will abandon the attempt, I need help with my java sdk. cant run javas games anymore!!!
i tried reintal it but didnt fix the issue

pi@pi:~ $ cd /home/pi/.tlauncher/
pi@pi:~/.tlauncher $ java -jar TLauncher-MCL.jar
[BootstrapStarter] Current dir: /home/pi/.tlauncher/.
[ProcessStarter] Starting process: [/usr/lib/jvm/java-8-openjdk-armhf/jre/bin/java, -Xmx128m, -Dfile.encoding=UTF-8, -classpath, /home/pi/.tlauncher/TLauncher-MCL.jar, ru.turikhay.tlauncher.bootstrap.Bootstrap]
[BootstrapStarter] Inherit process started
pi@pi:~/.tlauncher $

**Comment by lonemadmax** [comment]
My fault. I forgot a step.

nginx is dying because there's a reference to ssl certificates that have not been created:
<pre>
mar 09 00:45:03 pi nginx[2465]: nginx: [emerg] BIO_new_file("/etc/nginx/ssl/freeciv-web.crt") failed
mar 09 00:45:03 pi nginx[2465]: nginx: configuration file /etc/nginx/nginx.conf test failed
</pre>

At the end of the install you can see this message (among a lot of other stuff, so it's easy to fail to notice):
<pre>
- Point /etc/nginx/snippets/freeciv-web-ssl.conf to your certificate and key,
  or remove SSL support from /etc/nginx/sites-available/freeciv-web.
</pre>

You may remove `include /etc/nginx/snippets/freeciv-web-ssl.conf;` from `/etc/nginx/sites-available/freeciv-web`, edit it to take a certificate you may have, or even create a self-signed certificate with something like: https://github.com/freeciv/freeciv-web/blob/181fb2dcf4f068b72df78aa3594426782164e76e/scripts/install/install.sh#L311-L315

I've also noticed some freeciv compilation warnings about alignment. That's unrelated to this problem, but it may mean some internal structures are changed to accommodate the "different" architecture. If freeciv is not ready for that change, you may still be unable to play even after solving the freeciv-web issues.

**Comment by ghost** [comment]
Oke! I will. Test it on my dev microsd to avoid corrupt java again!

**Comment by andreasrosdalw** [comment]
Running the Freeciv-web server on Raspberry pi isn't a recommended way of running Freeciv-web.
Please point your web-browser to one of the servers running Freeciv-web, such as http://www.freecivweb.org/

**Comment by fonsecas72** [comment]
I know it's an old issue but just wanted to say that I have freeciv-web and server running on personal k8s cluster of rpis 4 (4GB)
Building the images however was not possible on 4 GB RAM. Seem I needed 4.5 GB so I had to use AWS VMs (a rpi with 8GB should be fine).
The only bit I missed from the build was to add "python3-dev". In case that helps anyone.

**Comment by andreasrosdalw** [comment]
@fonsecas72 Thanks for the update. Please submit a pull request to improve the build process if you know of how to improve it.
