### ISSUE TITLE
Bug in list of games in Metaserver - LongTurn game disappears from the list

### ISSUE THREAD

**Issue by andreasrosdalw** [freeciv/freeciv-web#253]
There is a bug in the list of games in Metaserver. 
The LongTurn game disappears from the list. Then sometimes it returns. 

This is the server list:
https://www.freecivweb.org/game/list?v=multiplayer

This is the link to the game:
https://www.freecivweb.org/webclient/?action=multi&civserverport=6061&civserverhost=fcweb&type=longturn

The game is actually still running. However, sometimes, it disappears from the list of games.

I also see this in the logs, not sure if it is related:
1: in sg_load_map_tiles_extras() [savegame3.c::2651]: Saved game contains incomplete map data. This can happen with old saved games, or it may indicate an invalid saved game file. Proceed at your own risk.
1: in sg_load_map_tiles_extras() [savegame3.c::2651]: last message repeated 2 times
1: in sg_load_map_tiles_extras() [savegame3.c::2651]: last message repeated 2 times (total 4 repeats)
1: in sg_load_map_tiles_extras() [savegame3.c::2651]: last message repeated 4 times (total 8 repeats)
0: in server_open_socket() [sernet.c::1212]: bind failure: Address already in use (2 failed)
0: in server_open_socket() [sernet.c::1212]: bind failure: Address already in use (2 failed)
0: in server_open_socket() [sernet.c::1212]: bind failure: Address already in use (2 failed)
0: in server_open_socket() [sernet.c::1212]: bind failure: Address already in use (2 failed)
0: in server_open_socket() [sernet.c::1212]: bind failure: Address already in use (2 failed)
0: in server_open_socket() [sernet.c::1212]: bind failure: Address already in use (2 failed)
0: in server_open_socket() [sernet.c::1212]: bind failure: Address already in use (2 failed)
0: in server_open_socket() [sernet.c::1212]: bind failure: Address already in use (2 failed)
0: in server_open_socket() [sernet.c::1212]: bind failure: Address already in use (2 failed)
0: in server_open_socket() [sernet.c::1212]: bind failure: Address already in use (2 failed)
0: in server_open_socket() [sernet.c::1212]: bind failure: Address already in use (2 failed)
0: in server_open_socket() [sernet.c::1212]: bind failure: Address already in use (2 failed)
0: in server_open_socket() [sernet.c::1212]: bind failure: Address already in use (2 failed)

@lonemadmax Feel free to log in to the server to check the logs. Also  can we please add some debugging code somewehere, to understand why it disappears?

**Comment by andreasrosdalw** [comment]
![Screenshot_20190310-103654](https://user-images.githubusercontent.com/41650711/54087455-3d38f400-4353-11e9-8fe7-9c5ff7440d73.png)

This might actually be a separate problem, but I will add it here now.
Some users also report that they are unable to join the game, and get the error message above. 
I also sometimes get the same error. Reloading the page solves it. Or waiting a while, then joining the game later, will solve the problem. -> Perhaps this is a problem where I try to join the game too often, and the connection is blocked because there should only be one connection for each player. In that case we need a better error message.

**Comment by lonemadmax** [comment]
The bind failure is freeciv server saying the port to listen from is already taken. Those only appear for ports 6000-6005.

I see five start-freeciv-web.sh processes, and I think there should be none (except when one is starting everything, of course).

All of that doesn't seem to be related with the problem with the longturn game. What I see is it disappears from the servers table. That should only happen for dead servers (autoclean for entries last updated more than 30 minutes ago) and when the server tells the metaserver that it is ending. Given that the game stays up... Lack of security. There were nearly a thousand entries like this in today's log:
<pre>46.4.40.175 - - [10/Mar/2019:19:41:09 +0100] "POST /meta/metaserver HTTP/1.1" 200 25 "-" "curl/7.47.0"</pre>

So someone upset with another Hetzner server and nothing better to do. Not pointing to anyone.

Haven't checked yet, but I guess the "invalid port validation" error is what you get when you try to connect to a game that doesn't appear in the servers table.

We should review what addresses need to be accessible from the outside and which shouldn't. There a check in https://github.com/freeciv/freeciv-web/blob/181fb2dcf4f068b72df78aa3594426782164e76e/freeciv-web/src/main/java/org/freeciv/servlet/Metaserver.java#L88-L96, but I guess it doesn't do what one may think it would do.
