### ISSUE TITLE
Use TypeScript in Freeciv-web

### ISSUE THREAD

**Issue by andreasrosdalw** [freeciv/freeciv-web#279]
Consider using TypeScript in Freeciv-web JavaScript client.
https://www.typescriptlang.org/

1. Modify generate_js_hand.py to generate TypeScript class definitions:
https://github.com/freeciv/freeciv-web/blob/develop/scripts/generate_js_hand/generate_js_hand.py

2. Use class definitions in JavaScript code, for example objects of Units, Cities, Techs.

3. Update build system to compile the TypeScript, for example TypeScript Maven Plugin:
https://github.com/ppedregal/typescript-maven-plugin
Or use an node.js based solution.

https://stackoverflow.com/questions/15363246/how-to-use-coffeescript-together-with-google-closure

Help wanted with this.

**Comment by mchenryc** [comment]
In response to the final link: Please ignore coffeescript, in favor of typescript

**Comment by andreasrosdal** [comment]
@mchenryc Interested in implementing this?

**Comment by mchenryc** [comment]
@andreasrosdal Would be interested in the typescript story, but my time has become limited. Perhaps when I can resurface :)
