### ISSUE TITLE
Vagrant build broken

### ISSUE THREAD

**Issue by andreasrosdalw** [freeciv/freeciv-web#285]
Vagrant build broken, this is in the logs:

=================================
Running Freeciv-web setup script.
=================================

Linux ubuntu-bionic 4.15.0-12-generic #13-Ubuntu SMP Thu Mar 8 06:24:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
basedir: /vagrant
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu Bionic Beaver (development branch)
Release:	18.04
Codename:	bionic

Default config parameters used
==== Installing Updates and Dependencies ====
apt-get upgrade
dpkg-preconfigure: unable to re-open stdin: No such file or directory
(Reading database ... 58278 files and directories currently installed.)
Preparing to unpack .../gcc-8-base_8.3.0-6ubuntu1~18.04.1_amd64.deb ...
Unpacking gcc-8-base:amd64 (8.3.0-6ubuntu1~18.04.1) over (8-20180312-2ubuntu1) ...
Setting up gcc-8-base:amd64 (8.3.0-6ubuntu1~18.04.1) ...
(Reading database ... 58277 files and directories currently installed.)
Preparing to unpack .../libgcc1_1%3a8.3.0-6ubuntu1~18.04.1_amd64.deb ...
Unpacking libgcc1:amd64 (1:8.3.0-6ubuntu1~18.04.1) over (1:8-20180312-2ubuntu1) ...
Setting up libgcc1:amd64 (1:8.3.0-6ubuntu1~18.04.1) ...
(Reading database ... 58277 files and directories currently installed.)
Preparing to unpack .../libstdc++6_8.3.0-6ubuntu1~18.04.1_amd64.deb ...
Unpacking libstdc++6:amd64 (8.3.0-6ubuntu1~18.04.1) over (8-20180312-2ubuntu1) ...
Setting up libstdc++6:amd64 (8.3.0-6ubuntu1~18.04.1) ...
(Reading database ... 58277 files and directories currently installed.)
Preparing to unpack .../libc6_2.27-3ubuntu1_amd64.deb ...
Unpacking libc6:amd64 (2.27-3ubuntu1) over (2.27-0ubuntu2) ...
Setting up libc6:amd64 (2.27-3ubuntu1) ...
(Reading database ... 58277 files and directories currently installed.)
Preparing to unpack .../base-files_10.1ubuntu2.5_amd64.deb ...
Warning: Stopping motd-news.service, but it can still be activated by:
  motd-news.timer
Unpacking base-files (10.1ubuntu2.5) over (10ubuntu1) ...
Setting up base-files (10.1ubuntu2.5) ...
Installing new version of config file /etc/issue ...
Installing new version of config file /etc/issue.net ...
Installing new version of config file /etc/lsb-release ...
Installing new version of config file /etc/update-motd.d/50-motd-news ...
motd-news.service is a disabled or a static unit, not starting it.
(Reading database ... 58280 files and directories currently installed.)
Preparing to unpack .../bash_4.4.18-2ubuntu1.2_amd64.deb ...
Unpacking bash (4.4.18-2ubuntu1.2) over (4.4.18-1ubuntu1) ...
Processing triggers for plymouth-theme-ubuntu-text (0.9.3-1ubuntu1) ...
update-initramfs: deferring update (trigger activated)
Setting up bash (4.4.18-2ubuntu1.2) ...
update-alternatives: using /usr/share/man/man7/bash-builtins.7.gz to provide /usr/share/man/man7/builtins.7.gz (builtins.7.gz) in auto mode
(Reading database ... 58280 files and directories currently installed.)
Preparing to unpack .../bsdutils_1%3a2.31.1-0.4ubuntu3.3_amd64.deb ...
Unpacking bsdutils (1:2.31.1-0.4ubuntu3.3) over (1:2.31.1-0.4ubuntu2) ...
Setting up bsdutils (1:2.31.1-0.4ubuntu3.3) ...
Selecting previously unselected package libzstd1:amd64.
(Reading database ... 58280 files and directories currently installed.)
Preparing to unpack .../libzstd1_1.3.3+dfsg-2ubuntu1_amd64.deb ...
Unpacking libzstd1:amd64 (1.3.3+dfsg-2ubuntu1) ...
Setting up libzstd1:amd64 (1.3.3+dfsg-2ubuntu1) ...
(Reading database ... 58285 files and directories currently installed.)
Preparing to unpack .../tar_1.29b-2ubuntu0.1_amd64.deb ...
Unpacking tar (1.29b-2ubuntu0.1) over (1.29b-2) ...
Setting up tar (1.29b-2ubuntu0.1) ...
(Reading database ... 58285 files and directories currently installed.)
Preparing to unpack .../dpkg_1.19.0.5ubuntu2.1_amd64.deb ...
Unpacking dpkg (1.19.0.5ubuntu2.1) over (1.19.0.5ubuntu1) ...
Setting up dpkg (1.19.0.5ubuntu2.1) ...
(Reading database ... 58285 files and directories currently installed.)
Preparing to unpack .../00-initramfs-tools-bin_0.130ubuntu3.8_amd64.deb ...
Unpacking initramfs-tools-bin (0.130ubuntu3.8) over (0.130ubuntu3) ...
Preparing to unpack .../01-initramfs-tools-core_0.130ubuntu3.8_all.deb ...
Unpacking initramfs-tools-core (0.130ubuntu3.8) over (0.130ubuntu3) ...
Selecting previously unselected package python3-netifaces.
Preparing to unpack .../02-python3-netifaces_0.10.4-0.1build4_amd64.deb ...
Unpacking python3-netifaces (0.10.4-0.1build4) ...
Preparing to unpack .../03-netplan.io_0.97-0ubuntu1~18.04.1_amd64.deb ...
Unpacking netplan.io (0.97-0ubuntu1~18.04.1) over (0.34) ...
Preparing to unpack .../04-grub-pc-bin_2.02-2ubuntu8.13_amd64.deb ...
Unpacking grub-pc-bin (2.02-2ubuntu8.13) over (2.02-2ubuntu8) ...
Preparing to unpack .../05-grub-pc_2.02-2ubuntu8.13_amd64.deb ...
Unpacking grub-pc (2.02-2ubuntu8.13) over (2.02-2ubuntu8) ...
Preparing to unpack .../06-grub2-common_2.02-2ubuntu8.13_amd64.deb ...
Unpacking grub2-common (2.02-2ubuntu8.13) over (2.02-2ubuntu8) ...
Preparing to unpack .../07-grub-common_2.02-2ubuntu8.13_amd64.deb ...
Unpacking grub-common (2.02-2ubuntu8.13) over (2.02-2ubuntu8) ...
Preparing to unpack .../08-friendly-recovery_0.2.38ubuntu1.1_all.deb ...
Removed /etc/systemd/system/sysinit.target.wants/friendly-recovery.service.
Unpacking friendly-recovery (0.2.38ubuntu1.1) over (0.2.37ubuntu1) ...
Preparing to unpack .../09-initramfs-tools_0.130ubuntu3.8_all.deb ...
Unpacking initramfs-tools (0.130ubuntu3.8) over (0.130ubuntu3) ...
Preparing to unpack .../10-libext2fs2_1.44.1-1ubuntu1.1_amd64.deb ...
Unpacking libext2fs2:amd64 (1.44.1-1ubuntu1.1) over (1.43.9-2) ...
Setting up libext2fs2:amd64 (1.44.1-1ubuntu1.1) ...
(Reading database ... 58302 files and directories currently installed.)
Preparing to unpack .../e2fsprogs_1.44.1-1ubuntu1.1_amd64.deb ...
Unpacking e2fsprogs (1.44.1-1ubuntu1.1) over (1.43.9-2) ...
Setting up e2fsprogs (1.44.1-1ubuntu1.1) ...
update-initramfs: deferring update (trigger activated)
(Reading database ... 58302 files and directories currently installed.)
Preparing to unpack .../libnss-systemd_237-3ubuntu10.24_amd64.deb ...
Unpacking libnss-systemd:amd64 (237-3ubuntu10.24) over (237-3ubuntu4) ...
Preparing to unpack .../libudev1_237-3ubuntu10.24_amd64.deb ...
Unpacking libudev1:amd64 (237-3ubuntu10.24) over (237-3ubuntu4) ...
Setting up libudev1:amd64 (237-3ubuntu10.24) ...
(Reading database ... 58302 files and directories currently installed.)
Preparing to unpack .../udev_237-3ubuntu10.24_amd64.deb ...
Unpacking udev (237-3ubuntu10.24) over (237-3ubuntu4) ...
Preparing to unpack .../libpam-systemd_237-3ubuntu10.24_amd64.deb ...
Unpacking libpam-systemd:amd64 (237-3ubuntu10.24) over (237-3ubuntu4) ...
Preparing to unpack .../systemd_237-3ubuntu10.24_amd64.deb ...
Unpacking systemd (237-3ubuntu10.24) over (237-3ubuntu4) ...
Preparing to unpack .../libsystemd0_237-3ubuntu10.24_amd64.deb ...
Unpacking libsystemd0:amd64 (237-3ubuntu10.24) over (237-3ubuntu4) ...
Setting up libsystemd0:amd64 (237-3ubuntu10.24) ...
(Reading database ... 58305 files and directories currently installed.)
Preparing to unpack .../0-libssl1.1_1.1.1-1ubuntu2.1~18.04.4_amd64.deb ...
Unpacking libssl1.1:amd64 (1.1.1-1ubuntu2.1~18.04.4) over (1.1.0g-2ubuntu2) ...
Preparing to unpack .../1-python3-lib2to3_3.6.8-1~18.04_all.deb ...
Unpacking python3-lib2to3 (3.6.8-1~18.04) over (3.6.5~rc1-1) ...
Preparing to unpack .../2-python3.6_3.6.8-1~18.04.1_amd64.deb ...
Unpacking python3.6 (3.6.8-1~18.04.1) over (3.6.4-4) ...
Preparing to unpack .../3-libpython3.6_3.6.8-1~18.04.1_amd64.deb ...
Unpacking libpython3.6:amd64 (3.6.8-1~18.04.1) over (3.6.4-4) ...
dpkg: considering deconfiguration of python3-distutils, which would be broken by installation of libpython3.6-stdlib:amd64 ...
dpkg: yes, will deconfigure python3-distutils (broken by libpython3.6-stdlib:amd64)
Preparing to unpack .../4-libpython3.6-stdlib_3.6.8-1~18.04.1_amd64.deb ...
De-configuring python3-distutils (3.6.5~rc1-1) ...
Unpacking libpython3.6-stdlib:amd64 (3.6.8-1~18.04.1) over (3.6.4-4) ...
Replacing files in old package python3-distutils (3.6.5~rc1-1) ...
Preparing to unpack .../5-python3-distutils_3.6.8-1~18.04_all.deb ...
Unpacking python3-distutils (3.6.8-1~18.04) over (3.6.5~rc1-1) ...
Preparing to unpack .../6-libexpat1_2.2.5-3ubuntu0.1_amd64.deb ...
Unpacking libexpat1:amd64 (2.2.5-3ubuntu0.1) over (2.2.5-3) ...
Preparing to unpack .../7-bzip2_1.0.6-8.1ubuntu0.2_amd64.deb ...
Unpacking bzip2 (1.0.6-8.1ubuntu0.2) over (1.0.6-8.1) ...
Preparing to unpack .../8-libbz2-1.0_1.0.6-8.1ubuntu0.2_amd64.deb ...
Unpacking libbz2-1.0:amd64 (1.0.6-8.1ubuntu0.2) over (1.0.6-8.1) ...
Setting up libbz2-1.0:amd64 (1.0.6-8.1ubuntu0.2) ...
(Reading database ... 58306 files and directories currently installed.)
Preparing to unpack .../libdb5.3_5.3.28-13.1ubuntu1.1_amd64.deb ...
Unpacking libdb5.3:amd64 (5.3.28-13.1ubuntu1.1) over (5.3.28-13.1) ...
Setting up libdb5.3:amd64 (5.3.28-13.1ubuntu1.1) ...
(Reading database ... 58306 files and directories currently installed.)
Preparing to unpack .../libmpdec2_2.4.2-1ubuntu1_amd64.deb ...
Unpacking libmpdec2:amd64 (2.4.2-1ubuntu1) over (2.4.2-1) ...
Preparing to unpack .../libncurses5_6.1-1ubuntu1.18.04_amd64.deb ...
Unpacking libncurses5:amd64 (6.1-1ubuntu1.18.04) over (6.1-1ubuntu1) ...
Preparing to unpack .../libtinfo5_6.1-1ubuntu1.18.04_amd64.deb ...
Unpacking libtinfo5:amd64 (6.1-1ubuntu1.18.04) over (6.1-1ubuntu1) ...
Setting up libtinfo5:amd64 (6.1-1ubuntu1.18.04) ...
(Reading database ... 58306 files and directories currently installed.)
Preparing to unpack .../libncursesw5_6.1-1ubuntu1.18.04_amd64.deb ...
Unpacking libncursesw5:amd64 (6.1-1ubuntu1.18.04) over (6.1-1ubuntu1) ...
Setting up libncursesw5:amd64 (6.1-1ubuntu1.18.04) ...
(Reading database ... 58306 files and directories currently installed.)
Preparing to unpack .../libsqlite3-0_3.22.0-1ubuntu0.1_amd64.deb ...
Unpacking libsqlite3-0:amd64 (3.22.0-1ubuntu0.1) over (3.22.0-1) ...
Preparing to unpack .../python3.6-minimal_3.6.8-1~18.04.1_amd64.deb ...
Unpacking python3.6-minimal (3.6.8-1~18.04.1) over (3.6.4-4) ...
Preparing to unpack .../libpython3.6-minimal_3.6.8-1~18.04.1_amd64.deb ...
Unpacking libpython3.6-minimal:amd64 (3.6.8-1~18.04.1) over (3.6.4-4) ...
Preparing to unpack .../dh-python_3.20180325ubuntu2_all.deb ...
Unpacking dh-python (3.20180325ubuntu2) over (2.20170125) ...
Setting up libssl1.1:amd64 (1.1.1-1ubuntu2.1~18.04.4) ...
Checking for services that may need to be restarted...done.
Checking for services that may need to be restarted...done.
Checking init scripts...
[1;24r(B)0[m[1;24r[H[J[1;1H[7m                                                                                [2;1H                                                                                [3;1H                                                                                [4;1H                                                                                [5;1H                                                                                [6;1H                                                                                [7;1H                                                                                [8;1H                                                                                [9;1H                                                                                [10;1H                                                                                [11;1H                                                                                [12;1H                                                                                [13;1H                                                                                [14;1H                                                                                [15;1H                                                                                [16;1H                                                                                [17;1H                                                                                [18;1H                                                                                [19;1H                                                                                [20;1H                                                                                [21;1H                                                                                [22;1H                                                                                [23;1H                                                                                [24;1H                                                                               [1;1HPackage configuration[5;2Hâ”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”¤ Configuring libssl1.1:amd64 â”œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”[6;2Hâ”‚[75Câ”‚[7;2Hâ”‚ There are services installed on your system which need to be restarted    â”‚[8;2Hâ”‚ when certain libraries, such as libpam, libc, and libssl, are upgraded.   â”‚[9;2Hâ”‚ Since these restarts may cause interruptions of service for the system,   â”‚[10;2Hâ”‚ you will normally be prompted on each upgrade for the list of services    â”‚[11;2Hâ”‚ you wish to restart.  You can choose this option to avoid being[11Câ”‚[12;2Hâ”‚ prompted; instead, all necessary restarts will be done for you[12Câ”‚[13;2Hâ”‚ automatically so you can avoid being asked questions on each library[6Câ”‚[14;2Hâ”‚ upgrade.[66Câ”‚[15;2Hâ”‚[75Câ”‚[16;2Hâ”‚ Restart services during package upgrades without asking?[18Câ”‚[17;2Hâ”‚[75Câ”‚[18;2Hâ”‚[20C<Yes>[23C<No>[23Câ”‚[19;2Hâ”‚[75Câ”‚[20;2Hâ””â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”˜[18;52HFailed to open terminal.debconf: whiptail output the above errors, giving up!
dpkg: error processing package libssl1.1:amd64 (--configure):
 installed libssl1.1:amd64 package post-installation script subprocess returned error exit status 255
dpkg: dependency problems prevent configuration of libpython3.6-minimal:amd64:
 libpython3.6-minimal:amd64 depends on libssl1.1 (>= 1.1.1); however:
  Package libssl1.1:amd64 is not configured yet.

dpkg: error processing package libpython3.6-minimal:amd64 (--configure):
 dependency problems - leaving unconfigured
Setting up libexpat1:amd64 (2.2.5-3ubuntu0.1) ...
dpkg: dependency problems prevent configuration of python3.6-minimal:
 python3.6-minimal depends on libpython3.6-minimal (= 3.6.8-1~18.04.1); however:
  Package libpython3.6-minimal:amd64 is not configured yet.

dpkg: error processing package python3.6-minimal (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 libssl1.1:amd64
 libpython3.6-minimal:amd64
 python3.6-minimal
No apport report written because the error message indicates its a followup error from a previous failure.
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by andreasrosdalw** [comment]
@lonemadmax maybe you can help?

**Comment by lonemadmax** [comment]
From what I'm reading, that's dpkg trying to get some answers but not getting a terminal. I can't test on bionic right now, could you try this?

```diff
diff --git a/scripts/install/deb.sh b/scripts/install/deb.sh
index 107ff4ce3b..7ab9a1442a 100644
--- a/scripts/install/deb.sh
+++ b/scripts/install/deb.sh
@@ -51,9 +51,8 @@ dependencies="\
   zlib1g-dev \
 "
 
-export DEBIAN_FRONTEND=noninteractive
 INSTALLED_TOMCAT=N
-APT_GET='apt-get -y -qq -o=Dpkg::Use-Pty=0'
+APT_GET='DEBIAN_FRONTEND=noninteractive apt-get -y -qq -o=Dpkg::Use-Pty=0'
 
 sudo ${APT_GET} update
 
```

**Comment by lonemadmax** [comment]
I had to remove my image and specifically point vagrant to an old one (still newer than the one in the report) to get a reproducer, but finally got it. If you are going to use it for anything other than testing the patch, you may want to just discard it and download the latest build.
