### ISSUE TITLE
Handlebars template issue preventing rendering of game window

### ISSUE THREAD

**Issue by YourDadsHusband** [freeciv/freeciv-web#293]
After cloning, building, and running the docker image I am unable to start any games or modify pregame settings, whenever I load the page with the game window I receive the following error in browser consoles:

Error: Template was precompiled with a newer version of Handlebars than the current runtime. Please update your runtime to a newer version (>= 4.3.0)

I attempted to update Handlebars from within the container but this did not resolve the issue.

**Comment by andreasrosdalw** [comment]
I get the same error. Pull requests welcome.

**Comment by vinaykapadia** [comment]
Changed the Handlebars file to 4.3.0, then searched for any reference to the file and updated that. Still no good, does the same thing.

**Comment by Lexxie9952** [comment]
Though I'm not using Docker, it may be of interest still.  I am running local copy of FCW with handlebars v4.0.11 and have no issues.

**Comment by andreasrosdalw** [comment]
Please confirm that this bug has been fixed in the latest develop branch,

**Comment by vinaykapadia** [comment]
Recreated Docker container with latest dev branch. It works now. Thanks!

**Comment by lonemadmax** [comment]
This may happen again in the future. How about forcing hb version in the install script to the same one used for the runtime?

**Comment by andreasrosdalw** [comment]
Great idea!
