### ISSUE TITLE
3D OpenGL not functioning

### ISSUE THREAD

**Issue by Scratchmang** [freeciv/freeciv-web#299]
OK,

  So the latest update resolved the game not starting issue. And it works fine in HTML5, But the 3d OpenGL just gives a black screen..

**Comment by andreasrosdalw** [comment]
Do you see an error message in the JavaScript console?

WebGL works here in this fork: https://github.com/lonemadmax/freeciv-web

**Comment by Scratchmang** [comment]
How do I open the Javascript Console?

Sorry, new to all of this.

**Comment by andreasrosdalw** [comment]
Google search for how, please.

**Comment by Scratchmang** [comment]
I'm not all that good with this. But here goes...

A cookie associated with a cross-site resource at <URL> was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at <URL> and <URL>.
freeciv.{My.Domain}/:1 A cookie associated with a resource at http://google.com/ was set with `SameSite=None` but without `Secure`. A future release of Chrome will only deliver cookies marked `SameSite=None` if they are also marked `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5633521622188032.


jquery.min.js?ts=2019-12-06T15:51:09Z:2 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ jquery.min.js?ts=2019-12-06T15:51:09Z:2
256[.WebGL-00000115654F9540] GL_INVALID_OPERATION: Feedback loop formed between Framebuffer and active Texture.
VM36:197 THREE.WebGLRenderer.render(): the renderTarget argument has been removed. Use .setRenderTarget() instead.


So I'm thinking something to do with Cookies and or Certificates?

Again I'm not a programmer by any means so I have very limited understanding of all this...

**Comment by Scratchmang** [comment]
> Do you see an error message in the JavaScript console?
> 
> WebGL works here in this fork: https://github.com/lonemadmax/freeciv-web

Downloaded and install....

Same results but now both the HTML5 and OpenGL don't work.

I'm beginning to think there's something I'm missing although with it being a Virtual machine I just don't know, would have thought spinning it up would be all it takes. :)

Oh well, I'll re-install the default version and see if I can get things working again, at least in the HTML5 version.

I suspect things will get sorted out eventually it's worth the wait, I understand that those doing the 'Back End' work have other things that are more pressing :)

My thanks to all you unsung heros :)

**Comment by Scratchmang** [comment]
OK,

More info (Hopefully it helps)

I wiped and reinstalled with the latest DEV build using the following command...

 git clone https://github.com/freeciv/freeciv-web.git --depth=10

Then "vagrant up"

which built a VM called...

freeciv-web_default_1576076668839_63773

All well and good so far. 

As it's a VM I had to forward different ports so the following two lines we added to the Settings of the Vagrantfile (Not sure if ti matters but thought i would mention it all the same)


config.vm.network :forwarded_port, guest: 80, host: 4848, host_ip: "192.168.42.211"
config.vm.network :forwarded_port, guest: 443, host: 5858, host_ip: "192.168.42.211"

And I can connect to the FreeCiv-Web server on port 4848 all well and good.

The HTML5 version works as it should. no issues there. 

The WebGL Version generates the following errors in the Java Log....

jquery.min.js?ts=2019-12-11T15:19:22Z:2 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

And then this one appears over and over... thousands of times.....

[.WebGL-0000019E08A7F160] GL_INVALID_OPERATION: Feedback loop formed between Framebuffer and active Texture.

And then these two errors repeat...

VM48:197 THREE.WebGLRenderer.render(): the forceClear argument has been removed. Use .clear() instead.
render @ VM48:197

VM48:197 THREE.WebGLRenderer.render(): the renderTarget argument has been removed. Use .setRenderTarget() instead.


If there's any more info I can add, please let me know....

**Comment by kvilhaugsvik** [comment]
Are you able to use WebGL on other people's Freeciv-web installs?

**Comment by andreasrosdalw** [comment]
This has been fixed in #301.

**Comment by Scratchmang** [comment]
Thank you!

Working as it should now.
