### ISSUE TITLE
vagrant up build doesn't work failing gcc: checking whether we are cross compiling: Permission denied

### ISSUE THREAD

**Issue by vliegnaarbeer** [freeciv/freeciv-web#307]
Please forgive my ignorance if I'm asking something stupid or in the wrong place. (Linux and C++ are not my usual area) 
I tried many different things to neutralise below crash when using the instructed "vagrant up" approach on a Windows 10 box using latest VirtualBox, Vagrant and tip of Free-Civ web branch: 

config.log:
configure:3807: checking whether we are cross compiling
configure:3815: gcc -o conftest -O3   conftest.c  >&5
configure:3819: $? = 0
configure:3826: ./conftest
./configure: line 3828: ./conftest: Permission denied
configure:3830: $? = 126
configure:3837: error: in `/vagrant/freeciv/freeciv':
configure:3839: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details_

My suspicion is that it is incorreclty concluding it is cross compiling based on the Permission error, but I don't get why as some of the steps before it already do some compilation tests, so I'm completely lost.

Among the things I tried was set Automount,  elevate user, switch off Windows defender, checking windows/linux line feed issues, etc.

**Comment by andreasrosdalw** [comment]
It looks like a file permission problem? In which directory did you check out Freeciv-web? Do you have write permission there?  Can you try running: 'vagrant ssh' and log into the Vagrant box, and see if you have write permission to the /vagrant/freeciv/freeciv directory?

**Comment by vliegnaarbeer** [comment]
Tx for your swift reply!
I tried that also, here did it again:
vagrant@ubuntu-bionic:/vagrant/freeciv/freeciv$ touch icanwrite
vagrant@ubuntu-bionic:/vagrant/freeciv/freeciv$ ls -l icanwrite
-rwxrwxrwx 1 vagrant vagrant 0 Apr 17 09:00 icanwrite

**Comment by andreasrosdalw** [comment]
This is fixed in the most recent version. Thanks for reporting.
Please try again, to verify that the problem has been solved for you also.
