### ISSUE TITLE
freeciv-web doesn't work after vagrant halt, vagrant up.

### ISSUE THREAD

**Issue by genewitch** [freeciv/freeciv-web#31]
virtualbox 5.0.14, installed freeciv-web using instructions on this page on windows. Is it possible to have the continuous integration tool restart the virtual machine and see if the server still passes tests?

The exact error is "Network error
Unable to communicate with civclientlauncher servlet. Error: error Internal Server Error null" when I click "start game" on the http://localhost/webclient/?action=new dialog that asks for your username.

**Comment by genewitch** [comment]
more info from vagrant SSH below. When i did a manual install this exact thing happened as well. i don't understand what service isn't working, because nginx is working (service running) - is this an ubuntu issue or a script issue, since this also failed on a manual install on ubuntu as well in the same way.

----LOG----

> root@vagrant-ubuntu-wily-64:/vagrant/scripts# ./stop-freeciv-web.sh
> Shutting down Freeciv-web: nginx, tomcat, publite2, freeciv-proxy, freeciv-pbem.
> Start freeciv-web on port 6048 and freeciv-proxy on port 7048.
> init-freeciv-web.sh port 6132
> Killed
> ../publite2/init-freeciv-web.sh: line 24: 10426 Killed                  freeciv-web --debug=1 --port ${2} -q 20 --Announce none -e -m -M http://${4} --type ${5} --read pubs  cript_${5}.serv --log ../logs/freeciv-web-log-${2}.log --saves ${1} ${pbemcmd:- } > /dev/null 2> ../logs/freeciv-web-stderr-${2}.log
> init-freeciv-web.sh port 6117
> unable to start freeciv-pbem
> unable to start meta-stats
> unable to start freeciv-earth-mapgen
> Enter password:
> root@vagrant-ubuntu-wily-64:/vagrant/scripts# ./start-freeciv-web.sh
> Starting up Freeciv-web: nginx, tomcat, publite2, freeciv-proxy.
> Starting nginx first.
> Please enter root password:
> nginx started!
> Starting php5-fpm
> starting php5-fpm
> Starting up Tomcat
> Starting publite2
> Will sleep for 8 seconds, then do a status test...
> starting meta-stats.py
> Starting Freeciv-Earth-mapgen.
> Publite2 started
> Starting Freeciv-PBEM
> Checking that Freeciv-web is running correctly...
> 
> 
> checking nginx on http://localhost
> nginx OK!
> 
> --------------------------------
> checking Tomcat on http://localhost:8080/
> Tomcat OK!
> 
> --------------------------------
> checking freeciv-proxy directly on http://localhost:7001/status
> --2016-04-18 04:09:36--  http://localhost:7001/status
> Resolving localhost (localhost)... 127.0.0.1
> Connecting to localhost (localhost)|127.0.0.1|:7001... failed: Connection refused.
> freeciv-proxy not running!
> 
> 
> 
> 
> 
> --------------------------------
> checking freeciv-proxy through nginx on http://localhost/civsocket/7001/status
> --2016-04-18 04:09:36--  http://localhost/civsocket/7001/status
> Resolving localhost (localhost)... 127.0.0.1
> Connecting to localhost (localhost)|127.0.0.1|:80... connected.
> HTTP request sent, awaiting response... 502 Bad Gateway
> 2016-04-18 04:09:36 ERROR 502: Bad Gateway.
> 
> freeciv-proxy not running correctly through nginx!
> 
> 
> 
> 
> 
> --------------------------------
> testing WebSocket connection directly to Tornado
> This should show "HTTP/1.1 101 Switching Protocols" and then timeout after 2 seconds.
> curl: (7) Failed to connect to localhost port 7002: Connection refused
> testing WebSocket connection through nginx
> This should show "HTTP/1.1 101 Switching Protocols" and then timeout after 2 seconds.
> HTTP/1.1 502 Bad Gateway
> Server: nginx/1.9.3 (Ubuntu)
> Date: Mon, 18 Apr 2016 04:09:36 GMT
> Content-Type: text/html
> Content-Length: 181
> Connection: keep-alive
> 
> <html>
> <head><title>502 Bad Gateway</title></head>
> <body bgcolor="white">
> <center><h1>502 Bad Gateway</h1></center>
> <hr><center>nginx/1.9.3 (Ubuntu)</center>
> </body>
> </html>
> 
> --------------------------------
>  checking freeciv-web / publite2
> freeciv-web not running
> 
> --------------------------------
> checking that webclient.min.js has been generated...
> webclient.min.js is OK!
> 
> --------------------------------
> checking that tileset has been generated...
> tileset is OK!
> 
> --------------------------------
> checking metaserver on PHP server...
> metaserver is OK!
> 
> --------------------------------
> Check of Freeciv-web is done!
> root@vagrant-ubuntu-wily-64:/vagrant/scripts#
>

**Comment by kvilhaugsvik** [comment]
Does it work before vagrant halt?

**Comment by genewitch** [comment]
reply to: https://github.com/freeciv/freeciv-web/issues/31#issuecomment-211381532

Yes. It works fine until the VM is stopped for any reason and then restarted.

**Comment by andreasrosdal** [comment]
This has been fixed now.  When running 'vagrant up' when Freeciv-web has already been built on Vagrant, then Freeciv-web will be started correctly. Please check out the latest source code and try again.

This is the relevant commit:
https://github.com/freeciv/freeciv-web/commit/43039d152c03ea7b7a100d7792905f65523e9f46

Thanks for the bugreport and interest in Freeciv-web, Genewitch! Perhaps you have some more things  you would like to see improved in Freeciv-web?

Andreas
