### ISSUE TITLE
Vagrant up Fails - 404 on box url

### ISSUE THREAD

**Issue by chezhouse** [freeciv/freeciv-web#318]
As far as I can tell, the most recent _Vagrantfile_ indicates that the box_url should be

`config.vm.box_url = "https://cloud-images.ubuntu.com/focal/20200804/focal-server-cloudimg-amd64-vagrant.box"`

However, I get a 404 when trying to access the remote file.
Is there a newer version of the box available or does it require specific credentials?

I am running on Windows in administrator mode when attempting the vagrant up

**Comment by andreasrosdalw** [comment]
I have fixed the URL now. So you may try to run Freeciv-web on the latest version.

(I will test the latest version now, to see if there are more errors in the Vagrant process)

Andreas
