### ISSUE TITLE
ENCRYPT has been removed from MySQL 8

### ISSUE THREAD

**Issue by andreasrosdalw** [freeciv/freeciv-web#319]
ENCRYPT has been removed from MySQL 8.

So Freeciv-web must be modified, by stop using ENCRYPT in MySQL and Crypt.crypt() in Java.

https://github.com/freeciv/freeciv-web/blob/develop/freeciv-proxy/freeciv-proxy.py#L170
https://github.com/freeciv/freeciv-web/blob/develop/freeciv-web/src/main/java/org/freeciv/servlet/NewPBEMUser.java#L136
https://github.com/freeciv/freeciv-web/blob/develop/freeciv-web/src/main/java/org/freeciv/servlet/LoginUser.java#L84

**Comment by andreasrosdalw** [comment]
@cazfi We need help with fixing this. 😊

**Comment by cazfi** [comment]
Does MariaDB still have it? Would it be an option to always use MariaDB instead of MySQL, even in distributions where also latter is present?

**Comment by andreasrosdalw** [comment]
Yes, MariaDB still has ENCRYPT():
https://mariadb.com/kb/en/encrypt/
So we could use MariaDB.

ENCRYPT() has been removed from MySQL:
https://dev.mysql.com/doc/refman/5.7/en/encryption-functions.html#function_encrypt

**Comment by andreasrosdalw** [comment]
MySQL recommends using SHA2() instead.

**Comment by andreasrosdalw** [comment]
Fixed in https://github.com/freeciv/freeciv-web/commit/3584523b584b18e236fefe86b72dcedbfa490648
