### ISSUE TITLE
New Logo?

### ISSUE THREAD

**Issue by elioqoshi** [freeciv/freeciv-web#32]
Hi there!

I'm Elio, Design contributor at Mozilla and Fedora. I was wondering whether you are looking for a new logo, as I'd love to create one for you. I have done dozens of logos for open source projects in the past and have developed videogames on my own before.

Here are some snippets:
https://dribbble.com/elioqoshi

What do you think?

**Comment by andreasrosdal** [comment]
Hello Elio!

I think it's amazing that you want to contribute a new logo for Freeciv-web! The artwork you posted a link to also looked good. I quite like the [current logo](https://github.com/freeciv/freeciv-web/blob/master/freeciv-web/src/main/webapp/images/freeciv-splash2.png), as well as the [front-page splash screen](https://raw.githubusercontent.com/freeciv/freeciv-web/master/freeciv-web/src/main/webapp/images/freeciv-fp-logo-3.png). However, if you could create some significantly better-looking, more high-resolution and more modern variants of these the logo and splash screen, that would definitively be a great improvement for Freeciv-web. Looking forward to see your proposal, and sorry about the late reply.

Andreas

**Comment by elioqoshi** [comment]
Hi @andreasrosdal , thanks for getting back! I have some quite busy 2 weeks ahead of me, but I will definitely give this a try later in May :)
Cheers,
Elio

**Comment by elioqoshi** [comment]
@andreasrosdal Sorry, this went off my radar, I can still do this.
