### ISSUE TITLE
Random autogame test failure

### ISSUE THREAD

**Issue by kvilhaugsvik** [freeciv/freeciv-web#35]
The autogame will sometimes fail to start. When the build is restarted on Travis everything works fine again.

(To avoid confusion: b90d3ebb853107839ba205fcbaa03e2b55a5e5f8 fixed the biggest cause of the random broken build emails from Travis today. This is a different cause that hasn't been fixed.)

**Comment by andreasrosdal** [comment]
What do you suggest we do?
We could disable autogames?
Do you have permission to rerun the build?

**Comment by kvilhaugsvik** [comment]
> What do you suggest we do?
I suggest that we live with the random failures until we find the cause. The vast majority of the random build failures today were caused by the problem b90d3eb fixes.

> We could disable autogames?
I would prefer to leave it enabled. The autogame test is useful. Today it identified a server crash. (build 1332)

> Do you have permission to rerun the build?
Yes. The problem b90d3eb fixes would sometimes require multiple restarts. This issue is much rarer. It only happened once. One restart fixed it.
