### ISSUE TITLE
key_unit_move(): broken auto disembark

### ISSUE THREAD

**Issue by kvilhaugsvik** [freeciv/freeciv-web#378]
key_unit_move() picks ACTION_TRANSPORT_DISEMBARK1 if the unit's type can do that action. If it can't it picks ACTION_TRANSPORT_DISEMBARK2. This is wrong because:

1) A unit may be able to do both actions in general but only ACTION_TRANSPORT_DISEMBARK2 in the current situation.

2) A unit may not be able to do any of those actions in the current situation but be able to do a third action that includes disembarking like ACTION_CONQUER_CITY2.

This breaks using the arrow keys to unload when key_unit_move() guesses that it should use an action to disembark the unit can't perform while another disembark action is possible.

Work around: pressing 'd' and clicking on the tile you want to disembark to.

**Comment by kvilhaugsvik** [comment]
Suggested complete solution 1: Stop trying to be smart. Show the user the action selection dialog.

Suggested complete solution 2: Do a background request to the server to find out what actions may be possible. Only choose for the player if an action is known to be possible. Show the action selection dialog if not.

**Comment by Lexxie9952** [comment]
does this affect current fcw.org with its current state of server ?

**Comment by kvilhaugsvik** [comment]
> does this affect current fcw.org with its current state of server ?

No.
