### ISSUE TITLE
Start using web_city_info_addition

### ISSUE THREAD

**Issue by kvilhaugsvik** [freeciv/freeciv-web#42]
The packet type web_city_info_addition was added to upstream Freeciv in Gna patch #7279. It takes care of extra city information Freeciv-web needs. It allows us to drop some Freeciv-web specific changes to Freeciv, including the patch that currently reverts it.

**Comment by andreasrosdal** [comment]
I agree.

**Comment by kvilhaugsvik** [comment]
Done in 27c4c61b0647fa9a550069e50681b17a49cceefe
