### ISSUE TITLE
Mech Inf icon is broken

### ISSUE THREAD

**Issue by ericcawthon** [freeciv/freeciv-web#440]
Shows next to "Mech. Inf." in action feed, as in "Your Mech. Inf. <broken icon> survived a brutal attack by a Rhenish <cruiser icon> Cruiser."

Observed on January 8th

**Comment by Lexxie9952** [comment]
Hi Eric. Thanks for reporting it. In future, the right repository for freecivweb.org is:

https://github.com/Lexxie9952/fcw.org-server

This issue does not exist on upstream freeciv-web and may be closed.
