### ISSUE TITLE
Docker install error 

### ISSUE THREAD

**Issue by Dhy19971** [freeciv/freeciv-web#442]
hi, i'm trying to install freeciv-web docker but i get a compile error. I don't know if it's the right place but can someone help me?
![img](https://user-images.githubusercontent.com/54805023/155858230-452b154a-488f-450e-94d8-5cfeec8acf3b.png)

this is my console output.
I follow exactly what I find in freeciv-web git hub
under the heading docker.

**Comment by andreasrosdalw** [comment]
https://github.com/freeciv/freeciv-web/pull/443

**Comment by Dhy19971** [comment]
solve
