### ISSUE TITLE
CMA in Freeciv-web

### ISSUE THREAD

**Issue by andreasrosdalw** [freeciv/freeciv-web#506]
Implement CMA in Freeciv-web.

![Screenshot_20220729-083958_Chrome](https://user-images.githubusercontent.com/41650711/181698826-03bd6538-5bc7-4c22-b176-a4755eb42d3a.jpg)

https://github.com/Lexxie9952/fcw.org-server/commit/caf342e5389cc4ef5663c684cac36c30bf25023a#diff-084184354ca98a010578f7d996d79bfbca0509e9a889e1e69535bc65e2bf1d79

https://github.com/Lexxie9952/fcw.org-server/blob/dev/freeciv-web/src/main/webapp/javascript/cma.js

https://github.com/Lexxie9952/fcw.org-server/blob/dev/freeciv/freeciv/common/networking/packets.def#L763

@cazfi Can you please help implement support for CMA for Freeciv-web in the Freeciv C server?

**Comment by cazfi** [comment]
What are you missing? I haven't tested server-side CMA much.

**Comment by andreasrosdalw** [comment]
The server side changes in this needs to be cleaned up and included in the Freeciv C server:
https://github.com/Lexxie9952/fcw.org-server/commit/caf342e5389cc4ef5663c684cac36c30bf25023a#diff-084184354ca98a010578f7d996d79bfbca0509e9a889e1e69535bc65e2bf1d79

**Comment by cazfi** [comment]
That commit seems to be mostly about backporting server-side CMA + completely unrelated changes.

Some of those network protocol parts have been dropped from freeciv since, as nobody was using them. Maybe we need to put them back.

**Comment by cazfi** [comment]
First server side change -> https://osdn.net/projects/freeciv/ticket/45268

**Comment by andreasrosdalw** [comment]
Yes, Freeciv-web needs a server side CMA. It should be fast and have a very simple API in the normal network packets system. If you will please add server side CMA to the Freeciv C server, then I can implement in Freeciv-web.

**Comment by cazfi** [comment]
The latter part is coming in -> https://osdn.net/projects/freeciv/ticket/45485

Most probably I can implement it before the end of week.

**Comment by andreasrosdalw** [comment]
Very nice! Also: www.fciv.net has been updated to the same version as freeciv/freeciv-web - so these are both compatible and running the latest Freeciv C server.

**Comment by cazfi** [comment]
> The latter part is coming in -> https://osdn.net/projects/freeciv/ticket/45485

The difference in the implementation there compared to one you linked is that I went for separate packets for setting cm parameter and clearing it, to avoid sending some dummy parameter data when one is about to remove the parameter.

**Comment by cazfi** [comment]
Do you have anything on the web-client side to share (make a PR about)?

**Comment by andreasrosdalw** [comment]
Here's a simple CMA for FCIV.NET 
 https://github.com/fciv-net/fciv-net/commit/e2da9ce69b284e243f80be516cd63d07a6329f55

This could be modified to be usable in Freeciv-web.

**Comment by cazfi** [comment]
Thanks. Started working on a port.
