### ISSUE TITLE
Revolution to republic government not possible 

### ISSUE THREAD

**Issue by andreasrosdalw** [freeciv/freeciv-web#511]
Revolution to republic government is currently not possible, because range 7 isn't implemented.

https://github.com/freeciv/freeciv-web/blob/develop/freeciv-web/src/main/webapp/javascript/requirements.js#L207

**Comment by cazfi** [comment]
This has been since fixed in https://github.com/freeciv/freeciv-web/commit/b0c77bffae95c2fc82d7e746a4ef2b8b12444f0a
