### ISSUE TITLE
Low-quality water shader

### ISSUE THREAD

**Issue by lmoureaux** [freeciv/freeciv-web#57]
There is a water shader at high quality, but it is disabled at lower qualities. Add a better fallback than just... nothing.

### Idea

Use a normal map of waves, two uniform vec2 *a* and *b*, one varying vec2 *uv*. In the pixel shader, fetch the texture at *uv* + *a* and *uv* + *b*. Use the mean of the two as normal vector. Animate *a* and *b* in JS (rotate and scale).
To avoid repetitions in space, one may consider adding some low-frequency, low-intensity noise (with non-integer wavelength). Repetitions in time can be avoided by tuning the JS animation.

I think GPU gems has a water shader, might be worth looking at.

**Comment by ghost** [comment]
All quality levels have the high-quality water shader now. Closing.
