### ISSUE TITLE
Savegame compatibility lost

### ISSUE THREAD

**Issue by mivdnber** [freeciv/freeciv-web#6]
The web client doesn't seem to recognize the game I saved yesterday before the new version was pushed. It's rather odd, because this is reported in the load dialog:
```
No savegames found. Please start a new game.
Savegame usage: 1146 of 5200 kB.
```
Is there any hope of restoring my game?

**Comment by andreasrosdal** [comment]
Hello Michiel. Unfortunately, the new version of Freeciv-web is not able to read savegames from the previous version. I'm sorry about this. It's the price of progress, given the limited number of developers on this game.

**Comment by mivdnber** [comment]
understand completely; you can't make an omelet without breaking eggs! I'm currently trying to get the savegame files in local storage to work locally, with limited initial success. I'll report back when I get it to work. Thanks!
