### ISSUE TITLE
Frontpage face-lift

### ISSUE THREAD

**Issue by adaxi** [freeciv/freeciv-web#61]
Facelift Demo
-----------------

In a previous pull request I stated that I would like to improve the front page and the metaserver pages. 
I ended up improving the design before doing structural work on the JSP logic.

https://adaxi.github.io/freeciv-demo/

This design has some qualities that facilitate the reworking of the JSP logic.

Motivation
-------------

Currently each page defines its own CSS and Javascript, which results in some duplicate code and hard to reuse code. To address this issue I would like to include the common code using JSP include directives.

The first step is to split CSS that is used on all pages from the CSS that is being used on specific pages. The demo page already incorporates that idea. This allows us to create the following template that incorporates styles, navigation and copyright:

```jsp
<html>
  <head>
	<%@include file="includes/head.jsp"%> <!-- Bootstrap/jQuery/FA -->
        <script></script> <!-- additional scripts for current page -->
	<link></link> <!-- additional scripts for current page -->
  <head>
  <body>
    <%@include file="includes/header.jsp"%> <!-- Navigation -->

    <!-- The page content goes here -->

    <%@include file="includes/footer.jsp"%> <!-- Copyright -->
  </body>
</html>
```
In this process I also attempted to reduce custom css code and reuse bootstrap components as much as possible, hence the face-lift.

I am 100% _not_ a designer but I think it turned quite OK. I have tested this under Firefox/Chrome in Debian, and should perform correctly on mobile devices. I have not tested on other platforms.

Next step
------------------

Should I continue my effort with this and start working on the JSP pages?

Contributing
---------------
Feel free to comment, or provide additional pull requests:
https://github.com/adaxi/freeciv-demo

**Comment by ghost** [comment]
Wow, this looks very nice! Please do continue on these improvements. Thanks!

**Comment by adaxi** [comment]
Thanks!
Next step will then be to integrate these ideas for the front page. After that I'll do the same for the metaserver.

**Comment by ghost** [comment]
Don't forget mobile/tablets and the ads also.

**Comment by adaxi** [comment]
How should I handle the new Chinese translations required for the frontpage?

**Comment by ghost** [comment]
I think that the Chinese pages will have to stay on the old design.
