### ISSUE TITLE
Password restore doesn't work

### ISSUE THREAD

**Issue by abbradar** [freeciv/freeciv-web#66]
Click on "Send password" button doesn't do anything visible (nor any e-mail arrives). Tested in Chromium and qutebrowser (based on Chromium).

**Comment by ghost** [comment]
I have not implemented this yet. Please send me your username and I will reset your password.

Patches to fix this is welcome.

**Comment by abbradar** [comment]
Thanks for clarification! I'll ask the person in question to contact you. Shall we leave this issue opened for now? 
-- 
Nikolay.

**Comment by ghost** [comment]
Yes, please leave the issue open.

**Comment by ghost** [comment]
This issue has been fixed now.
