### ISSUE TITLE
Unable to build due to gna.org being down

### ISSUE THREAD

**Issue by jacobrask** [freeciv/freeciv-web#71]
```
==> default: svn: E170013: Unable to connect to a repository at URL 'svn://svn.gna.org/svn/freeciv/trunk'
==> default: svn: E000110: Can't connect to host 'svn.gna.org': Connection timed out
==> default: Svn export failed
```

Would using http://repo.or.cz/freeciv.git work or should we wait until another mirror of gna is up?

**Comment by ghost** [comment]
Thanks a lot for suggesting this, I have updated the build script to use the repo your suggested. 
A better and more permanent repository will be available in a few days. Thanks!
