### ISSUE TITLE
Where does the music at freecivweb.org come from?

### ISSUE THREAD

**Issue by rvid19** [freeciv/freeciv-web#740]
Hi,
this is not really an issue (GitHub discussions isn't set up in this repo, and this looked like the next best place to ask this), but when playing at freecivweb.org, I was wondering where the music comes from, as I couldn't find it on any repository of these repositories:
[https://github.com/freeciv/freeciv-web/tree/develop](https://github.com/freeciv/freeciv-web/tree/develop)
[https://github.com/freeciv/freeciv/tree/main](https://github.com/freeciv/freeciv/tree/main)
[https://github.com/Lexxie9952/freeciv-web/tree/develop/](https://github.com/Lexxie9952/freeciv-web/tree/develop/)
In February, I found a way to get the URL of the currently playing song and download it, if you want. One example of the songs I managed to download is [https://www.freecivweb.org/music/middle/Palace2.mp3](https://www.freecivweb.org/music/middle/Palace2.mp3). In conclusion, I was wondering where they are located.

**Comment by andreasrosdalw** [comment]
The music on freecivweb.org is not open source. That fork of Freeciv-web is not focusing on publishing the full game with game resources and music.

Here are some Freeciv-web forks which prioritizes full open source licence compliance:
https://github.com/freeciv/freeciv-web
https://github.com/fciv-net/fciv-net

**Comment by rvid19** [comment]
Thank you for the information. :)
Also, any thought on setting up GitHub discussions?

**Comment by rvid19** [comment]
@andreasrosdal Thank you for the information. :)
Also, any thought on setting up GitHub discussions?

**Comment by andreasrosdalw** [comment]
@rvid19 I am focusing on the 3D version, which has GitHub discussions here: https://github.com/fciv-net/fciv-net/discussions

**Comment by rvid19** [comment]
Nice, I was taking a look.
