### ISSUE TITLE
Coinage improvement description in its tooltip is truncated

### ISSUE THREAD

**Issue by BujuArena** [freeciv/freeciv-web#775]
### **Steps to reproduce:**

1. View a city.
2. Navigate to the "Production" tab in the city view.
3. Hover the mouse cursor over the "Coinage" improvement.

### **Expected behavior:**

The "Coinage" improvement description in its tooltip is expected to contain only complete sentences and sufficiently describe the "Coinage" improvement.

### **Observed behavior:**

The "Coinage" improvement description in its tooltip says "This is not a normal improvement. Instead, setting a city" [sic].  The sentence "Instead, setting a city" is not a complete sentence and does not serve to sufficiently describe the "Coinage" improvement.

### **Screenshot:**

![image](https://github.com/freeciv/freeciv-web/assets/601517/0f39e568-6e23-4c7c-a887-84a1fad4a6c6)

**Comment by BujuArena** [comment]
This was observed on https://fciv.net/.  Please close this issue if observing an issue on that website is invalid.

**Comment by andreasrosdalw** [comment]
This bug has been fixed in Fciv.net now.

You are welcome to submit more bugreports to improve this game. Thank you for reporting!

The commit is here:  https://github.com/fciv-net/fciv-net/commit/f3d19e33edf348b596373dcd4d0c2583bd34ad67

**Comment by BujuArena** [comment]
Yup, looks fixed here.  Thanks!

![image](https://github.com/freeciv/freeciv-web/assets/601517/84d8cf79-c6fe-4182-95b1-2247ea3e5bc9)
