### ISSUE TITLE
show production below each city

### ISSUE THREAD

**Issue by rocifier** [freeciv/freeciv-web#9]
In Civ III, current production of each city is shown in a tag below each city. This is incredibly useful and stops one having to cycle each turn double clicking on each city to see where they are at, or what production they are currently running. Nice enhancement to have, and presumably easy to implement.

**Comment by andreasrosdal** [comment]
I agree, good suggestion!

**Comment by andreasrosdal** [comment]
This has now been implemented, and will be deployed to production soon.
